### ISSUE TITLE
need one more step to install firebase_auth plugin

### ISSUE THREAD

**Issue by adsequor** [dart-lang/pub-dartlang-dart#1164]
URL: https://pub.dartlang.org/packages/firebase_auth#pub-pkg-tab-installing

I suggest adding those steps in this install process :
Add this to your package's pubspec.yaml file:

dependencies:
  firebase_auth:

Install it

You can install packages from the command line:

with Flutter:
$ flutter packages get

Alternatively, your editor might support packages get. Check the docs for your editor to learn more.

**Comment by isoos** [comment]
These are on the https://pub.dartlang.org/packages/firebase_auth#-installing-tab- page. I'm not sure: what's the missing piece there?

**Comment by jakobr-google** [comment]
Looks like firebase_auth's README.md is linking to https://pub.dartlang.org/packages/firebase_auth#pub-pkg-tab-installing. Since that fragment doesn't exist, we show the package's main page (its README.md), which doesn't contain installation instructions.

Nothing we can do here, though. firebase_auth should link to https://pub.dartlang.org/packages/firebase_auth#-installing-tab- instead.

**Comment by isoos** [comment]
> shouldn't we be redirecting?

When we have changed the URLs it was considered to be low priority (the install tab is visible and one click away), partly because we were still on a JavaScript codebase as far as I remember it. I can do the redirect though, not much code is needed for it.

**Comment by mit-mit** [comment]
OK, I thought we had the redirects already. I think we should add them (the present bug is one example of how it can be confusing)
