### ISSUE TITLE
Analysis of package doesn't respect super-mixins

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/pub-dartlang-dart#1188]
https://pub.dartlang.org/packages/file#-analysis-tab-

The suggestions includes fixing analysis errors for things that aren't really errors.  The package [enables super-mixins](https://github.com/google/file.dart/blob/db0b529f55ef6b86e5af662f09ae854bfd93c42d/analysis_options.yaml#L6), which means that all the errors pub is reporting aren't actually errors.

**Comment by isoos** [comment]
Previous discussion: https://github.com/dart-lang/pub-dartlang-dart/issues/829

In short: we enable super-mixins for flutter packages, and ignore it for the rest, mainly because web packages can't use it (AFAIK it is still missing, but may have changed).

One way to handle this would be to first identify that the package is non-web, and then do a second analysis pass with the super-mixin enabled.

Another way would be the pass-through handling of the super-mixin setting in `analysis-options.yaml`, but that is still slightly wrong, because some packages would be classified as web, and won't work on web.

The correct way would be to enable super-mixin in `pana` for all, and then detect the actual use of super mixins, and if there is any, we remove the web platform label.

**Comment by tvolkert** [comment]
Supermixins don't work with DDC or dart2js, but they do work with the standalone VM.  Right now, `package:file` is marked as "FLUTTER" and "OTHER".  Not sure what the "other" is, but can we:

* Mark a package as just supporting flutter and VM?
* Enable supermixins for such packages?

**Comment by isoos** [comment]
Tracking in `pana`: https://github.com/dart-lang/pana/issues/288

**Comment by isoos** [comment]
Discussion on the pana issue indicates that super-mixins are going away, and something else will replace them. I'd suggest that you refactor the library and remove the use of supermixins.
