### ISSUE TITLE
Updated packages seems behind (3 days?)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1281]
Taken at ~5pm on Thursday.

![screen shot 2018-05-10 at 4 58 42 pm](https://user-images.githubusercontent.com/17034/39899936-72143402-5473-11e8-9be9-681b589b65d0.png)

csslib has been published twice today – but it's not showing up 😢

**Comment by isoos** [comment]
@kevmoo @jakobr-google: a reboot of the instances would mitigate the immediate problem again, but I'd also like to have that extra logging in a deployed version. Would it be possible?

**Comment by isoos** [comment]
I think the regression was caused by the new code that is now partially disabled: we do fetch the dartdoc-generated `index.json` from the `dartdoc` service, but don't use it in the search index. I think the symptoms in the log are consistent with a hanging `Future` where the `HTTP GET ... index.json` did not complete. https://github.com/dart-lang/pub-dartlang-dart/pull/1288 to fix that with a timeout.

**Comment by isoos** [comment]
#1288 seems to have fixed this. Package updates are now picked up in ~10 minutes or so.
