### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#14]
Sometimes the text layout is broken.

https://buildbot-dart-2015-04-22-dot-dartlang-pub.appspot.com/packages/bwu_docker

![image](https://cloud.githubusercontent.com/assets/405837/7478231/986b90ec-f359-11e4-8cd0-984dec37f3b3.png)

After a reload it is fixed.
Reopen in an icognito window it's broken again (not reliable reproducible).

I have seen this several times lately for different packages.
I also have this if I use the public URL but I don't have the URL available to explicitly load the Python version therefore I can't tell if this is Dart-only or not (assuming that the public URL might also run the Dart version occassionally).

**Comment by sgjesse** [comment]
As an FYI, the current direct link to the Python version is https://35-dot-dartlang-pub.appspot.com/ (App Engine application version is 35).

**Comment by mkustermann** [comment]
I think this is at least a rendering bug in chrome. [Which doesn't mean that package:mustache doesn't have an issue].

In particular: Using <ctrl-mouse-scroll> to zoom out and in again makes the rendering issue disappear. Firefox doesn't have this problem for me.

I'm tempted to mark this bug as AsDesigned. Do we have any reason to believe this issue is related to the server app?

**Comment by zoechi** [comment]
I guess this is stale.
