### ISSUE TITLE
please mark this is discontinued: analyzer_cli

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1443]
URL: https://pub.dartlang.org/packages/analyzer_cli

CC @devoncarew

**Comment by sortie** [comment]
Duplicate of #1399.

This has already been done. Due to a bug in pub, the package page was not regenerated after it was marked as discontinued. It will be fixed in the next deployment (tentatively today), which also should contain a fix, so newly discontinued packages don't have to wait for the next deployment.
