### ISSUE TITLE
Help with "recovering" a package that had a publisher removed

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub-dartlang-dart#1486]
https://pub.dartlang.org/packages/injector

I think we only support google accounts for authentication - is that correct? We allow you to add a publisher to a package with any email address, and I think it's possible to add an email that won't work because there is no way to authenticate as that email - if you add a non-google email and then remove the gmail as a publisher, does that package get stuck? Do we have any workarounds?

cc @kevmoo @nex3

**Comment by nex3** [comment]
There's always the workaround of asking someone with permissions to go into the database and manually change it.

**Comment by saibotma** [comment]
Can you please name me someone with permissions to go into the database? That would be awesome :)

**Comment by kevmoo** [comment]
I can, but it's very risky to do...

**Comment by saibotma** [comment]
Is there any other solution then?

**Comment by isoos** [comment]
/cc @mkustermann in EU timezone who could help (and hopefully not OoO).

We don't have a standard process for restoring accounts (yet), and unfortunately we don't have the audit log for such changes (yet), therefore we are on a bit of unknown. For this specific use case, you could contact a site admin on Google-internal channels (@sortie (OoO right now), @kevmoo or @mkustermann (temp fallback)), then the risk of package-hijack is not much, and they could re-add the gmail/google e-mail address.

Otherwise somebody needs to look into the Datastore entry of `PackageVersion`: `injector`/`0.0.1`, check the `uploaderEmail`, and restore that.

We have plans to improve this area, but right now this is the best we can do.

**Comment by saibotma** [comment]
Thanks for this extensive response. On what social media platform can i contact @sortie, @kevmoo and @mkustermann. I tried it on Gitter but i could just find @kevmoo.

**Comment by kevmoo** [comment]
I updated things. We should be all good now.

**Comment by jperezr21** [comment]
I have a similar problem. I was transferred ownership of [json_serializable_immutable_collections](https://github.com/jperezr21/json_serializable_immutable_collections) and in order to have a verified publisher account I used a domain which I no longer own. Now I can't publish new versions of these packages and I'm locked out of that publisher account forever (I forgot to add my gmail account as admin). How can I fix this?

**Comment by jperezr21** [comment]
Hi @isoos. My issue is totally related to this one. In fact, they're the same issue.

Thanks for the link to the pub.dev policy. Just sent an email to support@pub.dev describing my problem.

Cheers!

**Comment by knaeckeKami** [comment]
I am still admin of the demoda.app publisher and logged in

i think I can transfer ownership to a new publisher
