### ISSUE TITLE
Delete pub package

### ISSUE THREAD

**Issue by hkm-ricky-lau** [dart-lang/pub-dartlang-dart#1494]
Is it possible to delete a uploaded package inside the pub?

Thanks in advance.

**Comment by isoos** [comment]
The site admins are able to delete a package, but rarely do, because people may be depending on it already. The rare exceptions could be a non-usable package version.

If you have accidentally published security credentials, you can assume that it is already compromised and being stored in multiple places.

Do you have other reasons for the delete?

**Comment by hkm-ricky-lau** [comment]
@isoos Thanks for your reply.

I hard coded a testing API publish key inside the package, but I'd revoked the key. So, I'm not worried about that, but I wanna delete the package from the pub for good.

Do you know how to contact the site admins? If yes, could you share related information to me?

Thanks again.

**Comment by isoos** [comment]
@hkm-ricky-lau Please publish a new version without the key in it, that way people will likely depend on that latest. If there are no other worries, I'd just leave it like that. Otherwise this tracker is the best way to reach the admins, but this week most of them are out of the office, and it is likely that they will discuss this case only next week.

**Comment by hkm-ricky-lau** [comment]
I'd already published a new version to the pub. The last thing I worry about is the name of that package is flutter_stripe, which may misleading other users if they're searching for stripe related libraries. If it is not a problem, just leave it there.

Thank you @isoos
