### ISSUE TITLE
Remove facebook package from pub

### ISSUE THREAD

**Issue by Kleak** [dart-lang/pub-dartlang-dart#1563]
Is it possible to remove `facebook` package from pub.
I have rename it to  better match what it did here is the new one : [facebook_web_sdk](https://pub.dartlang.org/packages/facebook_web_sdk)

**Comment by isoos** [comment]
It seems that `facebook` is a popular package. I'd keep it around until all of the users migrate to the new one.

**Comment by sortie** [comment]
@Kleak I can definitely mark the package as discontinued if it won't be updated any more. You can update the README to point to the new package.

I'm not sure we'll want to delete the package. The initial version was uploaded Jun 6, 2018; which isn't very recent. No pub packages depends on this package, but user applications might. It currently has 57 of 100 popularity.

@isoos How easy is it for a package to get 57 popularity? Do I understand it correct this is just the normalized rank of the package in terms of downloads? So out of some 3600 packages, 57 popularity means it's the (100−57)÷100×3600 = 1548 top package? Looks like in my popularity data that this package has 19 unique downloads. So that's not a lot, but there are someone using it and removing it can cause breakages.

@mit-mit What package deletion policy do we have? So far I've only been removing very recent packages that aren't used. As soon as people start using a package, removing that package can cause breakages. Should we have a mechanism for more smoothly transitioning people to a new package? E.g. pub upgrade could warn people that the package now has a different name.

**Comment by Kleak** [comment]
You can mark it since all the following improvement will arrive in the new one.
I will update the README this week.

we are using it a lefty but we have already updated to the new one :)

**Comment by sortie** [comment]
https://pub.dartlang.org/packages/facebook has been marked as discontinued, it should soon show up as that on the website.

**Comment by isoos** [comment]
> So out of some 3600 packages, 57 popularity means it's the (100−57)÷100×3600 = 1548 top package?

Roughly that, but it is a bit better: only the active packages are considered, and those are <2000 I think.

**Comment by mit-mit** [comment]
@Kleak to make sure developer can locate your new package, I suggest you update the readme (https://pub.dartlang.org/packages/facebook) to link to https://pub.dartlang.org/packages/facebook_web_sdk
