### ISSUE TITLE
Mark Dart 2 incompatibility more promimently

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1574]
Now that we have had Dart 2 out for a bit, and scores adjusted accordingly, I'd like to go ahead and mark packages that are incompatible with Dart more clearly. I suggest we add a box-decoration to them similar to the platform boxes. The box should be red, and contain the text 'Dart 2 incompatible'.

**Comment by mit-mit** [comment]
sgtm short-term

**Comment by isoos** [comment]
I've realized that we already have a `legacy` status where we skip analysis entirely, and PR#1586 covers that use-case.

The next set of packages is where the package itself would allow the 2.0 SDK, but at least one of its dependencies is restrictive, e.g. `pkgA` depends on `pkgB` that doesn't allow 2.0. I have a bit of dilemma there, because the `pkgA` itself would be compatible with 2.0, and if its `pkgB` dependency would have a new release that allows 2.0, it would be all good.

We display a different analysis page for the above two cases:
- Package is legacy: https://pub.dartlang.org/packages/executor/versions/1.0.1#-analysis-tab-
- Dependent fails: https://pub.dartlang.org/packages/owl_codegen/versions/0.3.0#-analysis-tab-

The simplest way to have this changed is to switch the analysis status of the later case to `legacy`, and its error page would become just like the other one.

**Comment by isoos** [comment]
@mit-mit: this has been released. As we have voted to not include version resolution failures into this category (#1587), is there any package that we should also mark as legacy or can we close the issue?

**Comment by mit-mit** [comment]
I'm not sure I understand the reasoning here. Take the `owl_codegen` example above; it's confusing to an app developer what `[UNIDENTIFIED]` means, and if the package has dependencies that preclude using it with Dart 2, then the package is Dart 2 incompatible, isn't it?

**Comment by mit-mit** [comment]
Any chance we could push that fix out in a dot release? I'm working on a blog post that will talk about these new incompatibility tags.

**Comment by sortie** [comment]
We can do that. I'm a bit swamped with the testing workflow without status files, but it should be possible to deploy that code early-ish next week, and then leave it running overnight so everything is reanalyzed.

**Comment by isoos** [comment]
I've deployed this to staging: https://dartlang-pub-dev.appspot.com/

**Comment by isoos** [comment]
There is one more category of issues that would be under the umbrella of this issue: packages without SDK constraints. Our analysis does not depend on it, just analyses it, which will allow `pub upgrade` to go ahead, while depending on it will fail. They may just work, but SDK 2.0.0 (or 2.1-dev, not sure when it started) assumes their SDK constraint is <2.0.0, and depending on it will fail.

One example: https://pub.dartlang.org/packages/gun#-analysis-tab-

**Comment by isoos** [comment]
'gun' is now marked as incompatible with dart 2. I am not aware of any more edge cases, closing the issue.
