### ISSUE TITLE
Search box broken for this one weird page in analyzer docs

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dartlang-dart#1633]
Steps:

1. Load https://pub.dartlang.org/documentation/analyzer/latest/dart_element_element/LibraryElement-class.html

Expected results:

Search bar should be enabled, but it's disabled, with placeholder "Loading search...". Console has following:

```
Uncaught ReferenceError: module is not defined
    at typeahead.bundle.min.js:7
    at typeahead.bundle.min.js:7
highlight.pack.js:2 Uncaught ReferenceError: hljs is not defined
    at highlight.pack.js:2
URI.js:3 Uncaught ReferenceError: module is not defined
    at URI.js:3
    at URI.js:3
script.js:196 Uncaught ReferenceError: hljs is not defined
    at HTMLDocument.<anonymous> (script.js:196)
```

I tried CTRL+SHIFT+R, Incognito mode, no luck. This is with Chrome 69.0.3497.81 (Official Build) (64-bit) on Linux. Search seems to work for other pages, like https://pub.dartlang.org/documentation/analyzer/latest/dart_element_element/ClassElement-class.html.

**Comment by srawlins** [comment]
Phew, that makes sense; I can't imagine why else only _that_ page would be broken. Thanks @isoos !

**Comment by sortie** [comment]
It doesn't work for me. I see Javascript errors in the console.

```
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
LibraryElement-class.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/sourcesanspro/v11/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2
LibraryElement-class.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/sourcecodepro/v7/HI_SiYsKILxRpg3hIP6sJ7fM7PqlPevW.woff2
LibraryElement-class.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdu.woff2
typeahead.bundle.min.js:7 Uncaught ReferenceError: module is not defined
    at typeahead.bundle.min.js:7
    at typeahead.bundle.min.js:7
highlight.pack.js:2 Uncaught ReferenceError: hljs is not defined
    at highlight.pack.js:2
URI.js:3 Uncaught ReferenceError: module is not defined
    at URI.js:3
    at URI.js:3
script.js:196 Uncaught ReferenceError: hljs is not defined
    at HTMLDocument.<anonymous> (script.js:196)
```

**Comment by isoos** [comment]
Further debugging indicates that the issue is from a weird interaction of the imported JavaScript files and the generated `LibraryElement` page content, more specifically, around its `exports` field.

The following link contains the non-minified version of the typeahead content:
http://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js

Normally, the initialization route goes to the line `root["Bloodhound"] = factory(jQuery);`, however, in the case of `LibraryElement`, it goes to `module.exports = factory(require("jquery"));`, and then it fails with the exception trace pointed out above.

The reason it goes to that path is the `if (typeof exports === "object")` conditional, which coincides that the given class has `exports` field, which then translates to a `<dt id="exports" class="property">` HTML Element on that age. I suspect that jQuery somehow picks that up because of the id and creates a top-level object from it, but I haven't checked it in depth.

I'll move this issue to dartdoc, with the suggestion that in the long-term we should ship our own script that does similar feature for the generated docs.

**Comment by isoos** [comment]
This issue was moved to dart-lang/dartdoc#1776
