### ISSUE TITLE
Popularity score of 0, despite many users

### ISSUE THREAD

**Issue by renggli** [dart-lang/pub-dartlang-dart#1659]
The [XML](https://pub.dartlang.org/packages/xml#-analysis-tab-) package has popularity score of 0 despite the [many popular packages](https://pub.dartlang.org/packages?q=dependency%3Axml) that depend on it. This looks like a bug to me.

<img src="https://user-images.githubusercontent.com/131610/46144201-3a759700-c22a-11e8-86d9-1a24510e03bb.png" width="300"> <img src="https://user-images.githubusercontent.com/131610/46144205-3cd7f100-c22a-11e8-8590-09b172c26ffa.png" width="300">

**Comment by sortie** [comment]
Hi,

Thanks for the report!

The popularity data generation script had a limit of 2000 results in it, which cut it off when it got to the packages starting with 'T'. That meant 'xml' which starts with 'X' didn't get processed at all. I've removed the artificial restriction and rerun the popularity generation script. The site should pick up the change soon.

I'm keeping this bug open until the bug is confirmed fixed in production.

**Comment by renggli** [comment]
Nice, thanks a lot for the quick fix. The number looks much more realistic now:

<img width="400" alt="xml-popularity" src="https://user-images.githubusercontent.com/131610/46150423-8b8d8700-c23a-11e8-9ede-1a67cde662cd.png">

**Comment by sortie** [comment]
Super, great
