### ISSUE TITLE
Maintenance score takes significant hit when using git dependencies

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/pub-dartlang-dart#1669]
Since the release of Dart 2.0, I've had to fork a couple of projects which are no longer actively maintained in order to bump their SDK constraints. I refer to these forks directly in my pubspec.yaml, but it appears that pana takes off [40 points on my package's maintenance score](https://pub.dartlang.org/packages/draw#-analysis-tab-) for doing this.

What's recommended workaround for this situation? I imagine there's plenty of package authors who will run into similar issues.

**Comment by isoos** [comment]
@bkonyi: We'll soon land a change where we'll display the actual maintenance score impacts along the suggestions. In the case of the `package:draw`, there is a 20 points penalty for the unconstrained dependencies (*), and another 20 points for the too short description. With that change it will be clear that we've applied those scores. There is no penalty for being a fork, and we don't track forks (yet).

(*) In this case it is considered unconstrained because they are git based. Git project can disappear or change without the package user's control, and it is likely that we should apply even harsher penalties in such cases, as it reduces the long-term reliability of the package.

**Comment by bkonyi** [comment]
> @bkonyi: We'll soon land a change where we'll display the actual maintenance score impacts along the suggestions. In the case of the `package:draw`, there is a 20 points penalty for the unconstrained dependencies (*), and another 20 points for the too short description. With that change it will be clear that we've applied those scores. There is no penalty for being a fork, and we don't track forks (yet).
> 
> (*) In this case it is considered unconstrained because they are git based. Git project can disappear or change without the package user's control, and it is likely that we should apply even harsher penalties in such cases, as it reduces the long-term reliability of the package.

Ah, I didn't realize the short description had that large of a hit as well. Thanks!

With respect to the git based packages being considered unrestrained, is there a recommended workaround for dealing with packages which haven't (and likely won't) update their SDK constraints to support Dart 2.0? The ecosystem currently has plenty of packages which would work fine in Dart 2.0, but are unmaintained and have SDK constraints set for Dart 1.0.

**Comment by isoos** [comment]
>  is there a recommended workaround for dealing with packages which haven't (and likely won't) update their SDK constraints to support Dart 2.0? The ecosystem currently has plenty of packages which would work fine in Dart 2.0, but are unmaintained and have SDK constraints set for Dart 1.0.

If the package is something I care about, I usually reach out to the owner, and ask them if they want to maintain it. When they don't want to do that, they are usually cooperative to give ownership and uploading rights, and that means the package with the same name can be active again. Otherwise you can always pick a new package name...

**Comment by bkonyi** [comment]
> If the package is something I care about, I usually reach out to the owner, and ask them if they want to maintain it. When they don't want to do that, they are usually cooperative to give ownership and uploading rights, and that means the package with the same name can be active again. Otherwise you can always pick a new package name...

Ah, that's unfortunate... I was hoping to avoid re-uploading and some package owners are unresponsive. Oh well, if that's what needs to be done that's what needs to be done. Thanks for clearing it up!
