### ISSUE TITLE
Not finding changelog.md or readme.md, is the logic case sensitive?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#17]
The grinder.dart project has a changelog.md file. However, it's not being displayed on pub.dartlang.org: https://pub.dartlang.org/packages/grinder

Is the logic case sensitive and only looking for CHANGELOG.md ? If so, can we change it to be case insensitive?

Thanks for checking it out.

**Comment by sethladd** [comment]
Confirmed that the logic is case sensitive. Code is in backend.dart.

**Comment by sethladd** [comment]
Hi @mkustermann , since you are rocking the fixes to pub.dartlang.org, could you take a look at this one, too?

e.g. the readme for grinder isn't appearing: https://pub.dartlang.org/packages/grinder

Thanks!

**Comment by mkustermann** [comment]
Sure - even though IMHO it should really be `README.md` and not `readme.md` :'(

**Comment by sethladd** [comment]
Thanks! It's a left-over from the long-long ago. New packages use caps for README and CHANGELOG.

**Comment by mkustermann** [comment]
CL is up for review: https://codereview.chromium.org/1231673003/

But this has only an affect for newly uploaded packages, since the extraction of README/CHANGELOG happens during uploading. If really wanted, I could traverse existing packages and update them - though I'd prefer not to.

[The reason why I think this smells a lot is that if you have two files on linux 'CHANGELOG.md' and 'changelog.md' - which one is supposed to be used? There is ambiguity if one does it in a case-insensitive way]

**Comment by sethladd** [comment]
Thanks Martin!

**Comment by mkustermann** [comment]
For new uploads this should be handled. 

Let me know if you think it is really necessary to process all old packages and update their readme/changelog in case it's missing.

**Comment by sethladd** [comment]
It would be really nice to reprocess them. Not sure we can expect all package authors to reupload.

Also, thanks for the patch!

**Comment by mkustermann** [comment]
Should be done.

**Comment by sethladd** [comment]
Works for me! Really appreciate it.
