### ISSUE TITLE
Error: Exception: Homepage URL has no valid host: https://www.example.com

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1717]
In a request for `/api/packages/versions/newUploadFinish`, the following exception occurred:

```
pubserver.shelf_pubserver: An error occured while finishing upload.

Error:
    Exception: Homepage URL has no valid host: https://www.example.com

Stack:
    #0      syntaxCheckHomepageUrl (package:pub_dartlang_org/shared/urls.dart:111:5)
    #1      _parseAndValidateUpload (package:pub_dartlang_org/frontend/backend.dart:715:3)
    <asynchronous suspension>
    #2      GCloudPackageRepository._performTarballUpload (package:pub_dartlang_org/frontend/backend.dart:308:15)
    <asynchronous suspension>
    #3      GCloudPackageRepository.finishAsyncUpload.<anonymous closure>.<anonymous closure> (package:pub_dartlang_org/frontend/backend.dart:290:16)
    <asynchronous suspension>
    #4      withTempDirectory.<anonymous closure> (package:pub_dartlang_org/shared/utils.dart:46:16)
```

However, this is a user error (HTTP 400) rather than an event that should be logged as a warning.

**Comment by sortie** [comment]
Interesting, on subsequent retries this happened:

```
Error:
    DetailedApiRequestError(status: 404, message: No error details. HTTP status was: 404.)
```

Could this be the cause of #1680?

**Comment by isoos** [comment]
Oh, very likely as the pubspec has just that URL: https://github.com/jodinathan/input_mask/blob/master/pubspec.yaml

**Comment by isoos** [comment]
I think I know understand the sequence of events:
- On the first attempt to finish the upload, we throw a non-typed exception, and
  - We clean up the uploaded package archive.
  - It gets translated to a status code of 500.
- the `pub` client see the response and retries it another time:
  - The package archive is not there, we fail to read it, and throw a different non-typed exception.
- the `pub` client keeps retrying (5 times total)

Couple of moving parts were causing this effect:
- Prior to May/June, this wasn't an issue, because `pub` client did not retry on 500, only on 502, 503...
- There was also a change in pub_server that made a distinction between client-side problems and server issues. Client side issues get status code 400 and pub won't retry them.
- We have migrated most of our exceptions at that time, but some validation was added later that didn't follow that pattern and/or some validation were not migrated.

To fix this, I'll submit a PR that will use the proper exception for pub_server.

**Comment by isoos** [comment]
I've checked with a dummy publishing, and the pub client now displays the root cause:
```
Homepage URL has no valid host: https://www.example.com.
```
