### ISSUE TITLE
Investigate pkg/mustache4dart vs pkg/mustache

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#172]
mustache4dart seems to have picked up development recently.

Wondering if we'd want to be on something "fresher"

**Comment by isoos** [comment]
Is there any specific issue with the current `markdown` package that could be handled better in another package?

**Comment by kevmoo** [comment]
Zero. Just worried about bit rot. Low priority

From mobile. Sorry for brevity and/or spelling.

**Comment by mkustermann** [comment]
@isoos There is a difference between `markdown` and `mustache`. The original issue from @kevmoo was regarding `mustache`, which we only use for our html templates.

The readme/changelog files use `markdown` which is different and, afaik, supported/maintained by dart team.

Since we usually have little issues with the html templates, I see no reason for switching the mustache library.
