### ISSUE TITLE
Clicking the "api reference" link for a package redirects to the versions tab (only if it fails?)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub-dartlang-dart#1786]
I was trying to look at the [analyzer docs today](https://pub.dartlang.org/documentation/analyzer/latest/) for the latest version, but it just redirects you to the versions page without any error message.

I think it would be better to give an error that the docs haven't been built yet or failed to build, and then maybe a link to the versions page to try other versions.

**Comment by isoos** [comment]
This happens when dartdoc fails on the latest version, and the redirect happens so that the visitor can select another documentation version (the failed ones are marked as failed):

<img width="802" alt="screen shot 2018-11-15 at 17 21 55" src="https://user-images.githubusercontent.com/4778111/48566398-fbdf8d00-e8fa-11e8-9349-6e1197a275f6.png">

Would it help if we would mark the documentation links more prominently?

**Comment by jakemac53** [comment]
The issue is that it isn't obvious that there was an error that resulted in the redirect - (also the top 3 versions of analyzer do this redirect but only the first one has the "failed" message).

In my case I just assumed I clicked the wrong link, hit back, clicked it again, repeated, and the filed this issue haha.

A dedicated error page for this would be more appropriate imo, or possibly redirect to the version page but with a very obvious error banner or something explaining why you got redirected there.

**Comment by isoos** [comment]
Right. So far we have one bug and one feature request:
- Bug: `/documentation/analyzer/0.33.3+1/` redirects to the the `/latest/` URL, because the `isLatestStable` flag is not cleared (because the docs failed to generate). Because of this the status on the `/versions` page is displayed wrong.
- Feature request: display an error page, without redirect. Provide link to the `log.txt` and to the `/versions` page.

**Comment by isoos** [comment]
This has been deployed and fixed.
