### ISSUE TITLE
Searching for twitter does not return the twitter package

### ISSUE THREAD

**Issue by larryaasen** [dart-lang/pub-dartlang-dart#1809]
URL: https://pub.dartlang.org/packages?q=twitter

When searching for twitter the package twitter is not returned on the first page of results. However, when searching for tweet the package twitter shows up as the 3rd result. It seems that the search algorithm should return the twitter package as the 1st result when searching for twitter.

**Comment by isoos** [comment]
What @sortie described is correct. However, the `twitter` package is now at the top again, because there was a bug in the score/threshold calculation, and it was pushed even further back. If the package  will be without maintenance further, it will get lower scores, and eventually it will fall off again.
