### ISSUE TITLE
Placing email on public site is not safe

### ISSUE THREAD

**Issue by syberside** [dart-lang/pub-dartlang-dart#1883]
URL: https://pub.dartlang.org/packages/activatory

Email is not protected on pub site (placed in plain mailto link). This is unsafe and totally bad idea since any email extractor can find it.
I have removed email from pubspec, but it's still placed on pub site. Can I remove my email from pub completely?

I suppose this is a good idea to use some profile links (github?) but not emails.
For example, there are no emails on nuget (https://www.nuget.org/packages/AutoFixture/) and this doesn't seem like anyone has some problems with it.

**Comment by jonasfj** [comment]
>  Can I remove my email from pub completely?

At the moment no, that is not an option.

We have some ideas for how to make user-profiles and let people publish without using their email.
But right now email is the only trust point.

----
Personally, I don't attempt to keep my email address private, I trust in spam filters, since it easily ends up in mailing lists and bug trackers no matter what I do. In your case, your email is already publicly available in all our git commit messages.

```bash
$ git log
commit 3b3fe802e5cd86fde343d4e0c687c8fc873b90f3
Author: syberside <***********@gmail.com>
Date:   Mon Dec 17 02:56:14 2018 +0300

    Update .travis.yml
```
(I replaced your email with `***********`, so that I didn't leak it an extra time)

If you want to avoid this github has instructions on how you can use a no-reply address:
https://help.github.com/articles/about-commit-email-addresses/

**Comment by jonasfj** [comment]
For the record, this is something we want to see happen. I think the work is tracked in #1518.

Right now the whole user management is a little crude. I would love it if it was easier to find packages from the same author, etc..

**Comment by syberside** [comment]
Thanks for answering.
I think placing email in GitHub repo (in meta information, not in regular files) is secure enough. At least it is harder to extract.
Yep, #1518 will be nice feature. Also it will be nice to add token issuing interface to profile. But this sounds like independent feature.
