### ISSUE TITLE
Searches excluding Dart 1.x packages still include them

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1955]
For example, https://pub.dartlang.org/packages?q=email%3Amisc%40dartlang.org&page=15

**Comment by mit-mit** [comment]
![screenshot 2019-01-16 at 15 53 33](https://user-images.githubusercontent.com/13644170/51256964-e93f0e00-19a6-11e9-9961-a07581756189.png)

**Comment by jonasfj** [comment]
Think this is related to https://github.com/dart-lang/pub-dartlang-dart/issues/1952, and the other aspects of dart 2 compatibility cleanup we've been talking about.

**Comment by isoos** [comment]
#1977 fixes the "non-dart2" packages (the ones with incompatible SDK constraints), but there is still a small subset of packages where the pubspec indicates dart2-compatibility, but the dependencies themselves do not support it. One example is: https://pub.dartlang.org/packages/graphql_fetch_generator#-analysis-tab-

We've called them in a past chat as "broken" (because they could be working with Dart2 if their dependencies were getting a compatible update). Do we want to filter out these packages too? (Or just introduce a separate label for them?)

**Comment by isoos** [comment]
This is now fixed at staging, and will be part of the next prod release.
