### ISSUE TITLE
Viewport shifts when changing page

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#2021]
When switching between pages 10, 11, and 12 here (using the bottom navigation), the view port shifts up and down.

I think the reason is that some packages have descriptions that don't fit on one line. Can we show just the first x characters of these?

**Comment by isoos** [comment]
Which browser and which listing? When I click on the pages, it always goes "up" as if it were a new page load.

**Comment by isoos** [comment]
Ah, nvm, tested on lower zoom levels, I get the idea.

We are already capping the characters to the first-N of the description, but it can still result in different numbers of lines, depending the length. Not sure if there is an easy way to pick a fixed height... maybe a different height for different screen sizes.

**Comment by isoos** [comment]
There are a few layout conflicts that need to be resolved:
- on a desktop screen:
  - short description will be displayed on a single line
  - longer description will be displayed on two lines (we are cutting the length at 200 characters, and I haven't seen a package that took more than two lines).
- on a mobile screen these will be between 1-4 lines, maybe even 5.

As the issue is noticeable only on large screens, the solution should be either CSS-scoped to that, or it should work on all devices.

Some proposals, in preference order:

- We could add `min-height: 7em` to all of the package-boundary boxes, and that way enforce a minimum height on large screens. I have found the extra whitespace acceptable, but personal preferences may be different here.

- We could cut the length at 180 characters. `pana` actually warns the authors to not go over that, we could use it as a strict (and consistent) rule. It won't remove the issue, but will reduce the probability of occurrence.

- `text-overflow: ellipsis;` creates a single line of text, end when it reaches the bounding box, it will display `...` and cuts the rest. Scoped to large displays, this should be an easy solution, however, I find it really hard to read long texts like that.

- [line-clamp](https://caniuse.com/#feat=css-line-clamp) may worth to mention, but I think it would be beneficial only if all of our texts were much longer and we were aiming to display 2-3 lines of text.

**Comment by isoos** [comment]
@mit-mit please check this on the pub site if you still experience this viewport shifts.

**Comment by mit-mit** [comment]
Seems like it's fixed now, thanks!
