### ISSUE TITLE
camera plugin not listed

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#2053]
![image](https://user-images.githubusercontent.com/405837/52842820-93be6400-3100-11e9-98fc-8cb60d9ba9af.png)

Might just be an intermittent issue. I thought I report it anyway. 
Feel free to close if you think it only needs waiting for some job to run or similar.

**Comment by isoos** [comment]
Poking the search service, I was able to force the following exception, looking into it:

```
Error:
    NoSuchMethodError: The getter 'pkgScore' was called on null.
    Receiver: null
    Tried calling: pkgScore

Stack:
    dart:core/runtime/libobject_patch.dart 50:5                   Object.noSuchMethod
    package:pub_dartlang_org/search/index_simple.dart 258:47      SimplePackageIndex.search
```

**Comment by isoos** [comment]
The above exception is unrelated, it happened because of a URL query combination that is unreachable from the UI, I've queried the service backend directly.

The `camera` package is listed on page 7, which is clearly not good: https://pub.dartlang.org/packages?q=camera&page=7

**Comment by isoos** [comment]
Looks like the package score is off in the index, because we have 3 packages that were updated in the past 24 hours and they are in the back of the list when ordered by overall score:
https://pub.dartlang.org/packages?q=camera&sort=top&page=8

I'll investigate why Datastore scanning part of the index did not pick up the package scores (e.g. `firebase_ml_vision`, `camera`, `google_maps_flutter`). The daily index update should pick it up, so the issue should be gone by tomorrow at latest.

**Comment by isoos** [comment]
The fix was deployed to prod today, closing the issue.
