### ISSUE TITLE
discontinue pkg:memcache

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#2133]

**Comment by isoos** [comment]
It is a working package, and while not actively developed, I think it still qualifies as a useful thing. If we discontinue it, search on the site won't reveal it.

**Comment by kevmoo** [comment]
@mit-mit @jonasfj Here's the rub. It hasn't been touched since August.

travis is crashing. the analysis score is way down.

🤷‍♂️

**Comment by jonasfj** [comment]
The package talks about a old alpha service no longer being offered.

While the `memcached` client in the package is still useful, the package doesn't talk much about it.
If someone wanted to extract the `memcached` client and publish it as a `memcached` package that should be pretty easy.

If anyone wants the `memcache` package name, they are also free to just ask us :)

But since this is a "Dart Team" package I think it's best that we actively support it, discontinue it or transition ownership to an interested community member.. Or copy it to a repo outside the `github.com/dart-lang/` org and clearly label it an "unofficial google project".

(my rainy day todo list, for a very very rainy day, has a dream item about releasing the `memcached` client as a side project).

**Comment by jonasfj** [comment]
Done :)
