### ISSUE TITLE
Flutter package decreased score

### ISSUE THREAD

**Issue by tomwyr** [dart-lang/pub-dartlang-dart#2139]
After publishing a [package](https://pub.dartlang.org/packages/drag_list#-analysis-tab-) to the pub, the analyzer reports an issue about unused and missing import at the same time. In my IDE there's no issue reported and the code runs fine.

![health-issue](https://user-images.githubusercontent.com/9600796/54738342-25176f00-4bb4-11e9-92d0-8a935c47ff48.png)

**Comment by isoos** [comment]
In your `DragListState.dart` you use `import 'package:async/async.dart';`. This is available on your local machine, because it is pulled in by your `dev_dependencies` in the `pubspec.yaml`.

However, you'll need to specify such dependencies in your `dependencies:` block, because the users of your package will only fetch the ones that were specified there. Pub site first removes the `dev_dependencies`, and analyses the package with on the ones normally specified.

To fix the issue, add `async` to the dependencies block in your `pubspec.yaml`:

````
dependencies:
  async: ^2.0.8
  flutter:
    sdk: flutter
````
