### ISSUE TITLE
"Web" package mark as "Flutter"

### ISSUE THREAD

**Issue by alescdb** [dart-lang/pub-dartlang-dart#2161]
URL  : https://pub.dartlang.org/packages/basehref

Hi everyone,
I've just publish a web package (a web builder to be exact) but it has been tagged as a `Flutter` package and `Other` for some reason, so I can't find it in `Web` (not sure I'm clear :-)).

![image](https://user-images.githubusercontent.com/5646825/55242354-5855a000-523d-11e9-81e2-0429737c1ec2.png)

**Comment by isoos** [comment]
@alescdb: Your main library `basehref.dart` does not depend on a web API (e.g. `dart:html`), and it does depend (transitively) on `dart:io`. In such cases the outcome is what you see on the analysis, because your package can't be used on the web platform, despite the fact that you target the web platform.

You can follow #858 for similar examples, and possible future resolution.
