### ISSUE TITLE
Migrate documentation hosting to pub site

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#227]
Line up with new analysis engine. Take over ownership, etc.

**Comment by isoos** [comment]
Interesting case: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/tc_ou6znKgE
Based on the timestamps I would assume the upload completed later than dartdoc site got its notification, and that was the reason it could find and download the new version.

**Comment by kevmoo** [comment]
Yup...

**Comment by mkustermann** [comment]
@isoos How would dartdocs get a notification before the package was uploaded? The only way for dartdocs to find out about new packages atm is to poll e.g. `/api/packages` (or one of the other apis). Packages only show up there if they're committed in datastore. Our uploads happen within a transaction, so either they are committed or not.

So I'm not quite sure what happened, but seems worth investigating.

**Comment by kevmoo** [comment]
Could it be that the instance that was accessed had a stale memcache?

Since we have more than one instance...

**Comment by mkustermann** [comment]
There is a possibility of a memcache issue, where the upload happened on one VM (which invalidates it's memcache) and the fetch from the dartdocs happends to another VM.

Though I believe that if a client is requesting the tarball of a specific (package, version)-tuple, we will simply redirect to a google cloud storage URL (we don't first check if it exists, because GCS with just return 404 if it doesn't). So that's why it's a bit suspicious.

**Comment by isoos** [comment]
What's the expectation here?

1) Same as `analyzer`: re-generate docs with new `dartdoc` version every so often?
2) Generate docs at the time of the upload, and never bother to re-generate them again?

The current dartdocs.org site has docs generated with different versions of `dartdoc`, but most of it seems to be with a fairly recent version. (~ most packages I've checked was generated within a year or see, even though the package was several years old).

**Comment by mkustermann** [comment]
> What's the expectation here?

> Same as analyzer: re-generate docs with new dartdoc version every so often?
> Generate docs at the time of the upload, and never bother to re-generate them again?

We currently re-analyze packages "every so often" because:
  1) transitive dependencies change (3rd party packages, sdk, flutter sdk)
  2) the version of dartanalyzer changes

At least 2) will be the same, if we have a new dartdoc, we would like to re-generate documentation for packages (it would be quite weird otherwise).

The point 1) might not be necessary for dartdoc.

@kevmoo Any comments?

**Comment by isoos** [comment]
So, re-running the dartdoc every month or two seems to be just fine.

Where shall we store the timestamp of the last run? AFAICT there is no other state we need to store, except to upload the static files to the bucket that serves them eventually.

It could be just another file in the bucket... It contains a JSON map to be extendable, with the timestamp, and we could just fetch the file, check the timestamp, and decide whether a new (if missing) or a re-run (if old) is required. wdyt?

**Comment by isoos** [comment]
[This comment](https://github.com/dart-lang/pub-dartlang-dart/pull/322#issuecomment-326520223) was a good argument for version-namespaced dartdoc bucket.

However, with that, we'll need to:
- (1) control and track `dartdoc` versions in the pub site environment
- (2) keep track of what we consider 'official' version to display
- (3) keep track of the last N (N maybe 2?) versions and whether dartdoc had issues with it and should display the earlier version.

There are many low-priority edge-cases here (e.g. when and how to delete obsolete files), and I would like to have an incremental approach to start with (the first priority should be to fix the broken dartdocs.org site, even if we have some potential risks).

For the (1), we could use the [dartdoc package](https://pub.dartlang.org/packages/dartdoc), and that way SDK upgrade does not changes the `dartdoc` version without our control. With that, (2) should be a const in the deployed `dartdoc-frontend` (with the list of previously deployed versions too). Btw. shall we have a `dartdoc-frontend` service too? 

That leaves the question(3): what is the generic direction you'd like to see with the tracking of generated docs? E.g. we could:
- use similar mechanism to `analyzer`'s `PackageAnalysis` and `PackageVersionAnalysis`, with docs
- store the state in a metadata file in the bucket
- ?

**Comment by matanlurey** [comment]
Ping. We just made the Dart 2.0 SDK announcement, but you can't view any generated dartdoc...

**Comment by isoos** [comment]
A quick recap:

- Similarly to the `analyzer`, we'll need to re-generate docs for the same `package`, `version`, `dartdoc` triplet every month or so, to track the possible changes in their dependencies.

- As a contrast to the `analyzer` a new version of `dartdoc` should be rolled out with some coordination and batching, because it could cause changes in the style, and navigating from a package to another with a different style would feel weird.

- Ideally we should have some kind of garbage collection process that clears not only the old entries in the database, but also the generated files on the storage bucket.

Current high-level decisions ahead:

1. Decide on the path structure of the storage bucket. (e.g. `/package/version/dartdoc_version/timestamp/`)

2. Decide the database, e.g.
- storing a `.json` data in `/package/version`
- storing a `.json` in Datastore (under one- or two-level entity hierarchy)

Requirement: we'll need to know whether the new dartdoc version has been completed for all of the packages (all package versions).

3. Decide the switch mechanism for going from one dartdoc version to another, e.g.
- ad-hoc (easy to start with)
- database flag
- deploy flag

4. Decide on how many versions we'd like to keep (for a given `package/version`). I'd go with at most two, but there can be reasons to keep older dartdoc just in case.

**Comment by sethladd** [comment]
Just confirming, this will also handle packages that contain Flutter plugins, too?

**Comment by sethladd** [comment]
If you do end up producing API docs at a different URL, can we also setup redirects from the old location to the new location?

**Comment by isoos** [comment]
> Just confirming, this will also handle packages that contain Flutter plugins, too?

In the first version this will generate and host the output that `dartdoc` generates, on the same URLs that dartdocs.org has. I'm not sure whether running `dartdoc` produces documentation for the native Android or iOS code, if it does, we'll pick it up, otherwise it will need additional development.

**Comment by mit-mit** [comment]
Looking at the failures in a [sample](https://www.dartdocs.org/documentation/cloud_firestore/0.2.8/log.txt), I think we just need a more recent Flutter SDK that has a more recent pub, see https://github.com/flutter/flutter/pull/14436

**Comment by sethladd** [comment]
Thanks for checking @mit-mit 

@isoos eventually we'll want to generate docs for the platform code, but starting with generating docs for the Dart code helps!

**Comment by mit-mit** [comment]
Jakob to update the AppEngine dispatch config to prepare for the DNS switchover.

**Comment by kevmoo** [comment]
Awesome!

**Comment by isoos** [comment]
@jakobr-google: is there anything else to do here (e.g. redirecting dartdocs.org ?), or shall we close this?

**Comment by kevmoo** [comment]
It'd be good if redirect happened first – just for sanity.

**Comment by mit-mit** [comment]
DNS was updated, and everything is now served by pub. Redirect is tracked in https://github.com/dart-lang/pub-dartlang-dart/issues/1196.
