### ISSUE TITLE
Dart 1-only versions of packages have no API documentation generated

### ISSUE THREAD

**Issue by seanburke-wf** [dart-lang/pub-dartlang-dart#2280]
URL: https://pub.dev/packages/mockito#-versions-tab-

Currently, any version of a package which is not dart 2-compatible will have no API documentation generated, even when the docs previously existed. See the above URL for an example, where `mockito <3.0.0` has no dart 2 support.

**Comment by isoos** [comment]
This is to be expected: the pub site aims to provide the best up-to-date information about a package, with the current latest stable SDKs. Maintaining a full compatibility matrix is not a scope for us. For a while we have kept the generated documentation for old packages that are no longer useable with the latest SDK (either because of version constraint, or because they are have compile errors with the current SDK), but we are phasing that out, and removing such archives.

We have a few reasons for abandoning the documentation for such old versions: we are no longer able to adjust the styles, the markup metadata or the content policy on such generated content with a reasonable effort. As we want to expand the site features, we need to continuously strengthen the security of the user-provided content hosting, and the only sane choice is to focus only on the versions that are useable with the latest stable SDK.

**Comment by seanburke-wf** [comment]
This approach has caused us a fair amount of pain in the migration from dart 1 to dart 2. Many packages have breaking changes between their dart 1- and dart 2-compatible versions, including packages maintained by the Google Dart team, and it can be difficult to know whether specific API is available in both versions without access to dart 1 artifacts.

At the very least, I would expect some messaging about this on the pub documentation with some indication of how to get older documentation rather than a message about a build failure which looks like a bug. However, given that this is reference material, I would much rather look at old stylesheets than have it simply made unavailable.

**Comment by isoos** [comment]
Thanks @seanburke-wf for the feedback, we will consider when we would update the dartdoc generation and hosting (on our radar, but we have a few other things to do first).

**Comment by jonasfj** [comment]
Afaik, dart 1.x isn't getting any updates later... so if there was an XSS exploit in dartdoc shipped with dart 1.x, this would surface on the site.

I would suspect that you can run dartdoc on the contents of your `.pub-cache/` and have it write output to somewhere else.. Not that I have tried it.
