### ISSUE TITLE
Weird listing (out of order package?)

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#248]
See attached screenshot, currently from: https://pub.dartlang.org/packages?page=4

<img width="961" alt="screen shot 2017-07-24 at 1 46 46 pm" src="https://user-images.githubusercontent.com/4778111/28522016-8c255542-7076-11e7-8be8-504765f63cff.png">

The weird part is that the `angular_components` package is out of order. They should be listed in reverse of their last update times, yet, this package has an update time like a week back, without any new version published, listed around newer packages.

/ping @kevmoo @nshahan about the history of this package

**Comment by nshahan** [comment]
I believe the explanation is that I have published the package more recently but they were alpha versions. It must be ordered by publish date (stable or otherwise) but the date is only showing the last stable version that was published. 

For reference you can see the dates here on the tags I created when I publish: 
https://github.com/dart-lang/angular_components/tags

**Comment by isoos** [comment]
Ah, yeah, the [Versions](https://pub.dartlang.org/packages/angular_components#pub-pkg-tab-versions) tab doesn't show the new alpha version, it can be reached only from the [direct link](https://pub.dartlang.org/packages/angular_components/versions/0.6.0-alpha%2B1) of the url. And that doesn't show the publish date either.

@kevmoo: this is clearly confusing. (A) we shall not update the updated timestamp when we have new developer versions or (B) update the formatted timestamp and list it on the [versions](https://pub.dartlang.org/packages/angular_components/versions) page too.
