### ISSUE TITLE
Provide auto-updating popularity data to service

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#300]
Also mentioned here: https://github.com/dart-lang/pub-dartlang-dart/issues/154

**Comment by kevmoo** [comment]
@isoos can we start getting the infrastructure for this setup?

Datastore entities, etc. I'm working on getting a semi-automated way to get this populated. Just need an end-point.

**Comment by isoos** [comment]
With the current number of packages, this could be just a file in a bucket which the `frontend` and the `search` service will fetch in every few hours, storing the data in memory. Would you be fine with that, or go with a more robust solution?

**Comment by kevmoo** [comment]
My thinking: this will be done in one big dump ~weekly.

So adding to a bucket makes sense.

We could just set up the tool to upload w/ a timestamp and then the last
file wins. Makes it easy to undo a bad upload, etc.

**Comment by isoos** [comment]
sgtm

**Comment by kevmoo** [comment]
Doing the work to make this automatic is not in scope. We need to do it eventually, though...

**Comment by mkustermann** [comment]
Doing this work manually should not be an option. We can just put it into one of our existing services, maybe in a separate isolate and use datastore for coordination. They can just use the bigquery api to run the queries and write it to GCS.

As I've also pointed out [here](https://github.com/dart-lang/pub-dartlang-dart/pull/454#discussion_r146481634):

"""
Instead of listing the entire bucket contents, which can not only do several RPCs (under the hood), we should only try to fetch a `popularity-latest.json`.

The uploader should be able to upload as `popularity-YYYY-MM-DD.json` (so we have the historic values) and then do a compare-and-swap way to copy it over `popularity-latest.json`. There will be no races and everything is atomic: Either the new file is there entirely or the old file is there, this is guaranteed by GCS.

(Same is true for snapshots of search index: If we cache it on GCS I have probably added the same comment there)
"""

We might also want to gzip it, to get the file size down.

It's important to have `popularity-latest.json` to ensure our services can fetch it in `O(1)` instead of the linear searching which was proposed in https://github.com/dart-lang/pub-dartlang-dart/pull/454.

**Comment by kevmoo** [comment]
@mkustermann – I could modify the upload tool to upload the dated version and then update `popularity-latest.json` Let's track that in a separate issue, though.

We cannot run the popularity code entirely in app engine, though. We are using internal services to determine which requests are coming from bots & googlers

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/pub-dartlang-dart/issues/473

**Comment by isoos** [comment]
I believe this is done from the pub site's point of view. @kevmoo: do you need to keep the issue open for other part of the data feed?

**Comment by kevmoo** [comment]
Leave it open for "later". This is still a very manual process. It needs to get fixed...

**Comment by sortie** [comment]
I'm unclear what you want me to do here.

**Comment by sortie** [comment]
I've set up a local cronjob that runs every day at 13:30. Next I'll find a way to run this on a shared computer rather than my own.

**Comment by isoos** [comment]
Removed high priority, because the script seems to be running for a while now without issues.

**Comment by isoos** [comment]
@jonasfj can we close this issue?

**Comment by jonasfj** [comment]
yeah, this is done :)
