### ISSUE TITLE
Potentially get rid of artifical package health metric bias

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub-dartlang-dart#305]
The change in  https://github.com/dart-lang/pub-dartlang-dart/pull/302  introduced the health metric. For each package a "raw health" is determined based on pana/analyzer results.

Though the final health metric of a package is artificially modified based on the "raw health" metric of all other packages. The reason for this artificially introduced bias (which might decrease the "raw health" for some package and increase it for others) is not quite clear to me.

Instead of justifying it by "nodejs/npm does it" (if they even do use it for this purpose) we should think if it makes sense.

**Comment by isoos** [comment]
Another aspects:

Larger libraries have higher chances that they violate linter rules.  How should the score differ for a small and simple library with a few rules violated vs. a large and complex libraries with percentage-wise similar amount of linter rules broken? What about a large library with lot of rules broken vs. a small library that is just perfect according the tools?

I was thinking of a metric that somehow reflects the complexity, and the health score could reflect that "There were 5424 things that could have been broken in this packages, but only 23 minor ones are violated, so it should be good to go." With that, the score could be 5401/5424, instead of the 99.6% normalized score. The visual representation could be a two-sided bar with a logarithmic scale of the values involved.

However, it looks hard to come up with things that add up to the 5424 in this example, because the lines of code (even with stripping the comments and counting only full statements) is barely reflecting what could go wrong. Nevertheless, we could start with an inaccurate metric, and see where it leads us.

**Comment by isoos** [comment]
I think the following code health metrics would be useful for us:

- `magnitude`: The amount of code in the library, measured in "separate statement blocks". This should be in proportion to "How many things could go wrong with this code?".

- `complexity`: A metric on how structured the code is. Too many one- or two-liners? Many multi-screen methods? Several statements are packed together? There should be a balance in-between.

- `penalties`: The weighted sum of analyzer issues (lint infos have small weigh, code errors have larger weights).

To do it correctly we'll need a full code analysis (atm. we only do surface scan for the imported/exported libraries), which would make it slower to do.


For a "cheaper" solution, we could just go with the number of non-empty, non-comment lines, and a score for the linter penalties. wdyt?
