### ISSUE TITLE
Fix inconsistent view of package after publish (Memcached issue)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#318]
Since we have memcached running on each instance, an upload one place will remain unviewable to the other instances until their cache times out.

Not sure how to solve this is the short-term – but it needs to be solved.

Perhaps we spin up a GCE instance w/ a centralize memcache server?

**Comment by kevmoo** [comment]
CC @mkustermann @isoos

**Comment by isoos** [comment]
Option 1: A single-instance service with only a single memcache running. Because memcache has no cluster communication or sync, there is not much point to have multiple instances. There will be a network latency, but hopefully not much.

Option 2: appengine flex early access: "The Memcache service is currently not available for the App Engine flexible environment. An alpha version of the memcache service will be available shortly. If you would like to be notified when the service is available, fill out this early access form."

Option 3: Use a clustered distributed cache (optionally with a memcache-compatible interface).

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/pub-dartlang-dart/commit/90b2e3b55f37304cc00253be0387be57874b1ed5
