### ISSUE TITLE
Namespace memcache by service version?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#337]
See https://github.com/dart-lang/pub-dartlang-dart/blob/a0f4b6bc2921e1afe9406336efc516fa6199fd16/app/bin/service/frontend.dart#L97

Seems a good idea to treat a new roll of the service as a new namespace in memcache – ensure we don't hit stale package pages, etc.

Thoughts?

(Only matters once we go back to having a shared memcache service...)

**Comment by kevmoo** [comment]
CC @isoos @mkustermann

**Comment by mkustermann** [comment]
The namespace mechanism is (or I should rather say was) used to run a complete copy of the `pub.dartlang.org` site, with different data: The GCS bucket which stores the tarballs had different set of packages (different GCS prefix) as well as the datastore data was different (different keys, namely using the namespace dataset id).

I don't believe it is a good idea to let different versions use different memcache entries, because a new package uploads cause us to invalidate a number of memcache keys. If they are indexed by version, then some versions might be serving the stale versions.

**Comment by mkustermann** [comment]
For the reasons mentioned above (mainly cache invalidation should have effect on all versions), I think we should not do per-version caching.

Closing this issue.
