### ISSUE TITLE
Search service should not depend on analyzer

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#341]
A [recent PR](https://github.com/dart-lang/pub-dartlang-dart/pull/330) triggered a discussion and the plan is to refactor how search works and remove its dependency on analyzer.

My first thought is to:
- Introduce a `PackageSearch` object in Datastore, named similarly to `PackageAnalysis`.
- It would contain the data that needs to be indexed (`PackageDocument`) for each package.
- It would be populated and updated by the `analyzer` service, every time it completes analysis on the latest stable version.
- It would be polled by the `search` service roughly the same way the current pollers work, looking for recent updates via timestamp.
- The `search` service's snapshot is still worth to keep, so there is no change there.

I don't see a reliable alternative using the new 'global' memcache, because there is always a chance that a new version data gets evicted before any of the `search` instances pick it up, and we may wait for a month for a new analysis (if nothing else triggers it).

WDYT @mkustermann @kevmoo?

**Comment by isoos** [comment]
Wrt. the [trigger re-analysis of packages that depend on a new version](https://github.com/dart-lang/pub-dartlang-dart/issues/317), with the proposed solution above, the service dependencies would be these:
- `frontend` -> `search`, `analyzer`, `dartdoc` (trigger only)
- `analyzer` -> `search` (query dependees), `dartdoc` (trigger only)
- `search` (no service deps)
- `dartdoc` (no service deps)

**Comment by kevmoo** [comment]
SGTM

**Comment by mkustermann** [comment]
Firstly, we know for sure that there is some kind of `search -> analyzer` interaction, since search uses analyzer results for ranking. It can be a weak dependency, but it is there!

Yet, I still don't completely understand why there should be any `analyzer -> search` interaction at all. Analyzer doesn't need any full-text-search information (ever).

Generally speaking, it's better to not introduce a dependency, just because the other thing happens to have some information that could be useful somewhere else. This leads quickly to spaghetti code, which is even worse on bigger components. Clear separation of concerns seems much better to me and much more maintainable.

Another thing I don't understand, regarding transitive dependency information: To figure out which packages might need re-analysis, re-indexing, re-dartdoc, re-..., after a new package upload, one has to do a complicated computation. Even to just get a conservative estimate of what (package, version) tuples might resolve (transitively) to, via `pub get`, to the new upload is nontrivial. This computation seems more like a fixpoint calculation to me (you declare `A` depends on `B` if `B` appears in any of `A`'s pubspec.yaml files (i.e. any version) as a direct dependency. Then you run a fixpoint to get the transitive information, which can even contain cycles. The result is a conservative estimate on what needs to be re-{analyz,index,dartdoc,...}ed when a new package upload comes along.)

Will think a bit about this problem some more.

@isoos Maybe you could explain a bit more how you come up with the dependencies above.

**Comment by isoos** [comment]
> @isoos Maybe you could explain a bit more how you come up with the dependencies above.

Yeah, sure, apologies if I was vague, I probably hadn't spelled out everything in my head.

After your comment on the PR I've linked, I started to think what would be a really simple search service for us? If there were a search service on AppEngine flex, where we would just push our data every time a new analysis is completed. That's the simplest.

The next best thing is that we provide the index, a push the data the same way, however, we have some data consistency issues:
- AppEngine may kill the instances any time, we need permanent storage.
- AppEngine may start multiple instances, calling the API endpoint will load-balance between them. We need some kind of coordination and synching.

Putting entries in Datastore and polling them by the last update time seems to work for `analyzer`, so it should be fine here too. If the `analyzer` would populate this data, the `search` service does not require any other dependency. Technically this can be done either by the `analyzer` writing the entries to the Datastore, or by calling the appropriate `search` service API which does the same DB write.

That way the `search` keeps being simple, and the `analyzer` "knows" about it, in other words depends on it. Whether it should query the list of transitive dependees, is another question.

> Firstly, we know for sure that there is some kind of search -> analyzer interaction, since search uses analyzer results for ranking.

Yes, and we could implement the transitive dep. notification from `search`: when it picks up a new `PackageVersion`, it could use its internal index to look up all the packages that may need (fast-lane) re-analysis, and notify the `analyzer` about them.

I could go ahead with either approach, only one thing is in the negative here: multiple `search` instances will pick up the new `PackageVersion`, and trigger the same dependencies multiple times. As there is some of race-protection in the `analyzer`, this is not really an issue.

> transitive dependency information [...] which packages might need re-analysis, re-indexing, re-dartdoc, re-..., after a new package upload

Let's say `A` -> `B` -> `C` (`A` depends on `B` directly and on `C` transitively).

When `C` has a new version, both `A` and `B` should be re-analyzed. This will happen automatically every month or so, regardless of the new version in `C`, because we do re-analyze everything in every 30 days. We don't need to compute every version combinations, because each of them will be evaluated separately, given enough time.

However, for the latest version of `A` and `B`, it would be nice if such analysis happened right after the new version of `C` is uploaded. There are several scenarios here, e.g. a new version applies to the latest of `B`, but not to the latest of `A`, but fortunately (I believe) there is no package `D` that will start depending on `C` with this new version alone. So if we do our best guess and re-analyze the latest stable dependees, we cover the most interesting packages.

**Comment by isoos** [comment]
Ah, I forgot to address this: it depends on who notifies who. If `search` would notify `analyzer` about the transitive dependencies, the service-dependency graph would look like this:

- `frontend` -> `search`, `analyzer`, `dartdoc` (notify only) (same as above)
- `analyzer` ->  (no service deps)
- `search` -> `analyzer` (pull data, notify on transitive), `dartdoc` (notify on transitive)
- `dartdoc` (no service deps)

Either way, somebody needs to know about the transitive deps and either that or another one needs to notify the rest of services to re-do their stuff.

**Comment by isoos** [comment]
@mkustermann which way would you prefer?

**Comment by isoos** [comment]
Another option could be just to increase the analysis frequency of the latest stable versions. If they were to be analyzed every day, the `dependee` search wouldn't really matter. However, with that, we may need to make the "garbage collection" process more aggressive, e.g. it should only keep the latest `Analysis` for each pana/flutter combination.

**Comment by mkustermann** [comment]
> ... Whether it (analyzer) should query the list of transitive dependees, is another question.

Very nicely put. So we have two completely different tasks to solve:

   a) how do we get the analysis data to search service for ranking
   b) how does analysis (dartdoc, search, ...) service know when to re-analyze (re-dartdoc, re-search) after a new upload (i.e. what impact can that new upload have on existing analyzer/dartdoc/search results of (transitively) dependent packages)

The b) problem is what most of my concerns were about: It's a difficult problem to solve properly. So the question is do we really **need to solve** it at all? Do we really think that after a package upload we need to re-{analyze,dartdoc...} packages depending (transitively) on the new one? Do we really get value out of that? My feeling is we should keep it simple and not do it as long as we don't see clear benefit.

If we see a clear benefit of doing re-{analyze,dartdoc,...} of transitive dependents, then we can solve it, but in a proper way. As I tried explaining above, solving this problem requires being able to handle cycles in dependency graphs. Just saying, we record which packages depend directly (or indirectly) on a package and trigger a re-{...} can cause an infinite trigger chain due to cycles, effectively DoS-ing our service!

As also outlined above, the problem can be solved properly, by doing a fixpoint calculation on a lattice.

> Yes, and we could implement the transitive dep. notification from search: when it picks up a new
>  PackageVersion, it could use its internal index to look up all the packages that may need (fast-lane) 
> re-analysis, and notify the analyzer about them.

See above. I don't think search has the necessary information. If it would solve this task, then search would need to do the fixpoint calculation I mentioned!

Since we don't just want to re-analyze but maybe also re-{dartdoc,index,...} that transitive deps calculation functionality doesn't belong into the search service (and neither in analyzer, dartdoc, ...).

Also a new analysis result should not trigger a "new analysis causes search to re-rank, search tells analysis to re-analyze transitive dependencies, new analysis of transitive deps causes search to re-rank, ...."-cycle.


> Let's say A -> B -> C (A depends on B directly and on C transitively).

> When C has a new version, both A and B should be re-analyzed. This will happen automatically every 
> month or so, regardless of the new version in C, because we do re-analyze everything in every 30 
> days. We don't need to compute every version combinations, because each of them will be evaluated 
> separately, given enough time.

Correct. Again, do we think we get real value / benefit by doing it eagerly instead of eventually-consistent in 30 days.

> However, for the latest version of A and B, it would be nice if such analysis happened right after the 
> new version of C is uploaded. There are several scenarios here, e.g. a new version applies to the 
> latest of B, but not to the latest of A, but fortunately (I believe) there is no package D that will start 
> depending on C with this new version alone. So if we do our best guess and re-analyze the latest 
> stable dependees, we cover the most interesting packages.

Here you make all kinds of assumptions. Why is  `B` more important than `A`? Maybe `B` exports all of `C`s public members. So they have equal importance. Also there can be a cycle `A -> B -> C -> A -> B -> C` (by that I mean that `pubspec.yaml` of these 3 packages depend on each other with satisfiable constraints). There is nothing preventing that situation to occur!!! There is no DAG enforcement anywhere.


To sum up and make progress: Let's split this discussion into two discussions:

### Task 1. Should we re-{analyze,search,dartdoc} packages if any of there transitive dependencies got a new upload?

One use case for this is e.g. a new upload of a package marks classes/functions/methods/fields as `@deprecated`. This can have an impact on anything that directly or transitively depends on it. So maybe analyzer/dartdoc want to highlight that a package is now suddently using deprecated features.

-> My feeling is this is a problem which doesn't give enough value atm. @isoos @kevmoo wdyt? If you think we should implement, then let's start a discussion on another github issue about how to solve it.

### Task 2. How do we get data from analyzer to search

What data does search need? I assume it basically needs `lib/analyzer/models.dart:Analysis`. Since we need an analyzer result for a package in order to rank it, search could simply monitor analysis results. The simple solution, which works quite well so far, is to use polling. Search could poll new `Analysis` datastore entities and act if a new one comes along.


### (off-topic) Polling

At the point in time when we decide the polling solution in our code is no longer sufficient (either latency is too long -- which is just a few minutes atm, or rate of new items is too high -- currently we have only max 20 package uploads a day) then we could decide to switch to Pub/Sub. If we structure the code well, that switch could be as simple as changing a `DatastoreHeadPoller` with a `PubSubPoller`, in total just a few dozen lines. (The downside of using Pub/Sub combined with multiple versions of services and running code locally is that it causes extra complexity, quite possibly due to topic subscription management)

-> We always have the option, but let's only do it when we have a need for it.

**Comment by mkustermann** [comment]
Out of curiosity I have implemented a simple conservative fixpoint algorithm and run it on the prod packages. If I haven't made a mistake, there are `89` packages which have themselves as transitive dependencies. Granted, due to the conservative assumption here, some of these cycles wouldn't be able to exist in practice because their version constraints might not be satisfiable (my scripts unifies all dependencies from all versions for a package)

**Comment by isoos** [comment]
> Do we really think that after a package upload we need to re-{analyze,dartdoc...} packages depending (transitively) on the new one? Do we really get value out of that? My feeling is we should keep it simple and not do it as long as we don't see clear benefit.

I believe there is a value in providing analysis data about packages, because it shows that we care about certain values in the ecosystem. However, once the information we display is stale or obsolete, when you need to check whether any of its transitive dependencies have a new version, then the value diminishes. It is kind of like build status: I don't care if it was green 3 weeks ago, when it is broken right now.

Obviously there is a tolerance on the freshness: 1 month vs. 1 week vs 1 day vs 1 hour vs almost instantly. We started out with 1 month, because we were worried about how long it will take to analyze every package, but it turns out that we can scale it without Pub/Sub. There is a enough capacity in the current settings to re-analyze everything within a week, or re-analyze the latest stable versions every day. The "trigger-the-dependees" feature is important if we keep the general period in the 1-month range, and it becomes less important if we are closing on the 1-day-period.

Side note 1: I don't worry about cycles, because we don't trigger on new `Analysis`, rather on new `PackageVersion` (or rather `PackageVersionAnalysis`), and the transitive dependee list without versions is straightforward List.where, no recursion. Having said that, I agree that if we can get by without these, let's do that. Not because it is hard (or rather: hard to prove that it's correct), but because we can achieve the same result with more frequent analysis periods.

Side note 2: I believe strong mode dart-analyzer emits at least a notice about using deprecated API, so we already have that info in the pana results.

My takes:

- [Task 1] Let's keep the current setup as long as it suits us, but increase the frequency. It may be the latest stable versions only, but bringing those closer to 1-day refresh is covers most of my worries. (Both for analyzer, dartdoc and whatever else comes up, a 1-day refresh should cover most of the worries about transitive effects.)

- [Task 2] `search` could poll new `Analysis` items, or call the `analyzer` REST API so that it doesn't need to know about the internals of it. Either way is fine and will do it. At the same time, we shall get rid of the `analyzer` -> `search` notification, because by polling the `Analysis` we won't need it anymore, and it removes the only sneaky dependency in this direction.

**Comment by mkustermann** [comment]
> ... "garbage collection" process more aggressive
> ... bringing those closer to 1-day refresh is covers most of my worries

Do we even have a garbage collection atm? I don't remember that we do. Preferably the code is written in a way which makes this unnecessary (we only write new `Analysis` objects if there is not already one with the same contents). 

Don't think it would be good doing it every day, in particular not if we write the result unconditionally to the DB.

> Side note 1: I don't worry about cycles, ... and the transitive dependee list without versions is 
> straightforward List.where

This is exactly the point I don't believe is true. A simple `List.where` does not ever give you the correct answer! For each package you got back from the `List.where` you have to search again to find it's dependents. Which is precisely the fixpoint iteration I was talking about. (even hacks like looking into all package versions's `pubspec.lock` files and see if the newly uploaded package name appears, does not give the correct answer)

> I believe there is a value in providing analysis data about package

Since you think it's important to have that functionality, I might spent some time to implement this in an encapsulated way. Then the analyzer service can do this calculation by itself without contacting any other services and has a relatively precise answer (it will probably be a conservative superset).

> [Task 2] search could poll new Analysis items, or call the analyzer REST API so that it doesn't need to know about the internals of it.

SGTM

**Comment by isoos** [comment]
> Do we even have a garbage collection atm? 

We do, although this is certainly not the most polished part of our stack.: https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/bin/service/analyzer.dart#L100

It is running once every week (per analyzer instance, assuming that appengine will keep it running that long). A proper cron-ified service would be better, but at the moment it is not really a pressing issue.

**Comment by isoos** [comment]
> For each package you got back from the List.where you have to search again to find it's dependents.

Ah, I see where you are coming from. The good part is, that `pana` and `pub` solves part of this problem already. Let me explain:

- `A` depends on: `B`, `C`, `D` directly
- `B` depends on `X`, Y` directly

During the `pana` analysis, we will resolve everything and record in the results that `A` has the following dependencies: `B` (d), `C` (d), `D` (d), `X` (t), `Y` (t), marking each of them as direct (d) or transitive (t).  We "inverted-index" this list, which already has all of the transient ones resolved, and with that a single lookup will get us all of them, no recursive lookup is needed.

**Comment by mkustermann** [comment]
> Ah, I see where you are coming from. The good part is, that pana and pub solves part of this problem 
> already.

Thanks for explaining, now I understand how you wanted to implement it.

> Let me explain: ....

Let me explain why this will give you only a subset of dependencies: Pana does not consider all versions of all direct/indirect dependencies (if I understood the code correctly). Therefore all [pana::scanTransitiveLibs()](https://github.com/dart-lang/pana/blob/master/lib/src/library_scanner.dart#L136) is doing is finding `.dart` files, looking at import/export declarations, rinse and repeat until everything was found (which is in someway also a fixpoint iteration).

Though the issue is that the procedure that pana is doing here runs entirely on those (package, version) tuples that a `pub get` checked out. It doesn't consider any other versions of the transitive dependencies. Though a new upload of one package (which is not included in this transitive closure that pana reports), can suddently make a version (of a package that is included in the transitive closure that pana reports) constraint satisfy, thereby selecting the newly uploaded package.

To finally make an even more concrete example:

```dart
A (the package we do the analysis on) depends on:
  B ">= 1.0.0 <2.0.0"

B 1.0.0 depends on:
   C "^1.0.0"

B 1.1.0 depends on:
   Y ">= 1.0.0 <2.0.0"
   Z ">= 1.0.0 <2.0.0"

Y 1.0.0 depends on:
   Z ">= 0.0.1 <1.0.0"
```

Now before `package:pana` does it's work on package `A`, it will do a `pub get` or `pub upgrade` of `A`. 

`pub upgrade`s constraint solver first tries to use `B 1.1.0` (because it prefers higher versions of dependencies) but figures out it's not satiable because `B 1.1.0` has a constraint on `Z`  (namely `>= 1.0.0 < 2.0.0`) which is incompatible with the constraint `Y` has on `Z` (namely `>=0.0.1 < 1.0.0`).

Therefore `pub upgrade`s constraint solver will just go with `B 1.0.0` which has just `C` as a dependency and all constraints satisfy. `package:pana` therefore says: `A` depends directly on `B` and indirectly on `C`.

Now a new package upload of `Y` happens, as follows:
```
Y 1.0.1 depends on:
  Z ">= 0.0.1 <2.0.0"       # <--- the author of Y has widened the constraint on Z
```

Now we **need to run a new analysis of**  `A`, because that new analysis will suddently pick `B 1.1.0` (since it became satiable now).

Clearly the transitive dependencies that `package:pana` reports is not good enough to be used for determining which packages need re-analysis! qed

**Comment by mkustermann** [comment]
I will implement code in order to solve this problem, so we can avoid eager analysis of all packages every day and the GCing of datastore entities.

**Comment by isoos** [comment]
> Clearly the transitive dependencies that package:pana reports is not good enough to be used for determining which packages need re-analysis! (it might be that I made a mistake when thinking this through, if so, please point it out!)

`pana` reports the dependencies in two levels:

The first one is the **package-level** dependencies, and these are reported in their full transitive closure of packages. This is mostly coming from `pub upgrade`, and it is stored in the `pkgResolution` [field](https://github.com/dart-lang/pana/blob/master/lib/src/summary.dart#L87) which is essentially a list of [PkgDependency](https://github.com/dart-lang/pana/blob/master/lib/src/pkg_resolution.dart#L281) entries describing the version constraint, the resolved and available versions and type (e.g. direct vs. transitive).

The second one is the **library-level** dependencies, coming from the `scanTransitiveLibs` method you mentioned, and these are reported per-[file](DartFileSummary) (per-library). The transitive list of libraries is used for platform-classification of that source file (library). And later on the per-file libraries will be used to classify the package-level platform.

My understanding is that you were thinking of this later library-level dependencies, and I agree, they are unreliable for the identifying the dependee list. However, my earlier suggestions were based on the package-level dependencies, which handles the case of `Z` being introduced in the new version of `Y`.

Does this explain the different takes?
