### ISSUE TITLE
Vanishing comments in markdown code blocks

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dartlang-dart#37]
In the [`oauth2` package's README](https://pub.dartlang.org/packages/oauth2), all lines but the first in block comments in the README seem to have vanished. I can't reproduce this with the [`markdown` package](https://github.com/dart-lang/markdown) alone, so I guess it must be something in the server?

**Comment by sgjesse** [comment]
This is a problem for all packages.

At the moment the pub-site use a custom version of markdown due to upstream patches were slow to land. This should have been fixed with the transfer of ownership of that package, so we can probably get rid of the custom version.

However the issue might of cause not be related to the custom version of markdown used.

**Comment by mkustermann** [comment]
This is same issue as #26
