### ISSUE TITLE
Task: process for search tuning

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#428]
When I search for `travis` I get a bunch of unrelated results - https://pub.dartlang.org/search?q=travis

`yaml` - https://pub.dartlang.org/search?q=yaml – the first many are fine...then analyzer, js, html, quiver

Instead of filing a bunch of one-off bugs, I'd like to find a process for how we tune this...

**Comment by isoos** [comment]
Hah, I like these bug reports so much better than "hey, my package is not in the search index" 🔍 

I don't have a suggestion for a process, because we haven't had too many requests of this yet. But let's debug these results and see where it goes:

Travis scores:
- [text-only](https://search-dot-dartlang-pub.appspot.com/search?q=travis&indent=true&order=text): this puts the travis package clearly at the top. My suspicion is that the rest of the results have a link to travis-ci in the first part of their readme, and thus they are considered relevant.

- [overall](https://search-dot-dartlang-pub.appspot.com/search?q=travis&indent=true): This shows what we've got after the popularity and health metric factored in. The way we do this is a weighted sum.

I see one low-hanging fruit here: the popularity and health metric should not be added to the weighted sum, rather it should be multiplied to it.

However, for the travis-ci links, the only thing that solves it is a true TF-IDF scoring.

I believe some of the earlier changes reduced the memory use of the search index, right now we have it around 354MB in prod and 320MB in staging. It looks like we can safely introduce a few more counters and that will give use the true TF-IDF scoring, which should filter out the travis-related results.

**Comment by kevmoo** [comment]
We're just looking at the raw markdown, right?

Crazy idea: we could parse the markdown into HTML – and then parse the html and only get the text content.

So URLs pointing to travis aren't counted.

Just pondering...

**Comment by isoos** [comment]
Yeah, that is a good point, and it will solve *this* particular issue, but otherwise it won't do much good for the rest.
