### ISSUE TITLE
mdl package without icon

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/pub-dartlang-dart#441]
https://pub.dartlang.org/search?q=mdl

Shows no icon - any ideas why? It should have an HTML (WEB) icon

**Comment by isoos** [comment]
The package analysis was incomplete, because:
````
pub upgrade failed.
ERR: Could not find package mdl_grinder at \"/Volumes/Daten/DevLocal/DevDart/MaterialGrinder\".
Depended on by:- mdl
````

**Comment by isoos** [comment]
Btw. similar error is present for the last few versions, maybe this is not a recent change...

**Comment by matanlurey** [comment]
It looks like many of the dependencies are local `path`:

https://github.com/MikeMitterer/dart-material-design-lite/blob/master/pubspec.yaml

I'm surprised `pub` let this upload at all.

**Comment by MikeMitterer** [comment]
Thanks for pointing out this error @isoos! 

@matanlurey Most of the path-commands are commented out. mdl_grinder has a path dependency but this is a dev_dependency so in my opinion this shouldn't be a problem.
The l10n is only temporary in the master.

**Comment by matanlurey** [comment]
If `pub get` will fail on this package, there is no (good) way to analyze it unfortunately.

**Comment by kevmoo** [comment]
We could get silly w/ [pana](https://github.com/dart-lang/pana) here – if pub get fails we could delete dev_dependencies and try again.

Hacky, but maybe okay?

**Comment by isoos** [comment]
> We could get silly w/ pana here – if pub get fails we could delete dev_dependencies and try again.

It opens up a lot of reliability questions, eg.:

- I've used e.g. `postgresql` as dev dependency, as part of a multi-db package. If I have a path dependency there, and we remove the entire dev block, the postgres-related libraries won't get analysis either way, while the rest will yield a result that is probably not correct. If we remove only the path-based deps, it still puts a hole in the list of libraries we can reliably analyze, and the package-level analysis is compromised.

- What if you add a `dev_dependency` as a mistake, while you are developing, but in reality you do have a normal dependency on that package? We want to detect that too, and making rules about the `dev_dependencies` less strict won't help with that.

- If I want to "vendor" the dependency (e.g. copy the sources into my own source code control in order to make patches that work on my code), such dev dependencies won't get resolved.

I think it is fair to say that path dependencies are for local developments, and they shouldn't be in a published package, because there is no way you can reliably resolve them on a clean host. I'd stick to that, and encourage maintainers to clear up the pubspec files.

**Comment by MikeMitterer** [comment]
As in my case the devdependency "mdl_grinder" has some internal scripts and packages to generate my samples. It makes absolutely no sense to publish this package to pub

**Comment by isoos** [comment]
For me, it doesn't make much sense to depend on an unpublished package either, and I see very little reason to support such use-cases. I believe `pub` should block publishing such packages.

@MikeMitterer : Removing the non-public dependency is the straightforward option, and whether you publish your internal scripts is up to you to decide. E.g. you could have them in the git repository, but move it temporarily every time before publishing. (Its a slightly bit annoying, but it became a habit for me to check the list of the published files before hitting yes to confirming everything).

**Comment by MikeMitterer** [comment]
@isoos Dev-Dependency is a dependency only for development purpose. Thats why they made it. Thats the reason why there is a dependency-section and a dev-dependency-section.
pub should simply ignore this part.

As you said - it's annoying to change the path every time before publishing just because there is a bug in "pub publish" or how they generate the icons. Thats the place where the bug should be solved.

**Comment by isoos** [comment]
I believe these two paragraphs describe our situation here:

From [dev dependencies](https://www.dartlang.org/tools/pub/dependencies#dev-dependencies):

> The rule for deciding between a regular or dev dependency is simple: If the dependency is imported from something in your lib or bin directories, it needs to be a regular dependency.

From [path packages](https://www.dartlang.org/tools/pub/dependencies#path-packages)

> Path dependencies are useful for local development, but do not work when sharing code with the outside world—not everyone can get to your file system. Because of this, you cannot upload a package to pub.dartlang.org if it has any path dependencies in its pubspec.

Which takes precedence? As the practice shows, `pub` did allowed you to upload the package, and I've also checked: `pub` blocks publishing if I have a path in direct dependencies. In other words: `pub publish` ignores `dev_dependencies`, and the analyzer should do the same. I've filed https://github.com/dart-lang/pana/issues/103 for tracking this in `pana`.

**Comment by isoos** [comment]
This would also address my previous concerns, because:

- The dartlang site is clear that my use of `postgresql` in a multi-db package was wrong.
- If one uses a normal dependency as a `dev_dependency`, it should be brought up by the analysis and this is a good way to do that.
- Vendoring the `lib/` and `bin/` directories still works. Testing may not, but that seems to be not really a concern from the pub site's point of view, so that downside is negligible.

**Comment by kevmoo** [comment]
Looks like @MikeMitterer fixed his package – which makes confirming that our latest deployment fixes this more difficult.

...but I do think our latest deployment fixed this.

@isoos – okay to close?
