### ISSUE TITLE
Task: include split-out popularity for flutter_cli access

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#466]
When sorting by popularity, flutter users should see packages ranked by only flutter_cli access

**Comment by isoos** [comment]
Before going into the implementation details:
- (1) Do we have data that says this causes a different distribution of results?
- (2) If it does have a different distribution, what is the difference, and can we do it in another way?

My gut feeling is that somebody would like to rank flutter-exclusive packages higher than generic packages, but I'm not convinced that (a) this can be achieved by such ranking, (b) this is something that is worth to diverge from the otherwise symmetry of our platform handling.

**Comment by kevmoo** [comment]
I'm running through the experiment now. Stay tuned...

**Comment by kevmoo** [comment]
Things I've learned:

- Slitting out flutter vs not-flutter is huge. We actually get several flutter-specific packages in the top 10
- We should not count "any" imports at all. Just direct and dev

I'm working on a PR now

**Comment by isoos** [comment]
@kevmoo: I believe this is implemented. Is there anything else, or can we close?

**Comment by kevmoo** [comment]
Looks good! Thanks!
