### ISSUE TITLE
Ability to see both stable and dev release versions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub-dartlang-dart#47]
Related to issue #46, if you visit https://pub.dartlang.org/packages/polymer you now see only the stable version, not the release candidate version. These are very different, and have totally different readme files etc.

I think maybe the best solution would be to actually have two different pages? Maybe stable is still the default but it has a link to a page for the dev version?

**Comment by jakemac53** [comment]
Hmm now also on the versions page the dev releases are being pushed below all non-dev releases? This makes things even more confusing....

**Comment by mkustermann** [comment]
This was implemented in f360308c8cf4c41f8124b4c80b1f28469ce6f7fa due to a request by @munificent.  The pub commands (e.g. `upgrade`) will use this ordering when doing version constraint checking, so it seemed to made sense to have the same ordering on the web page.

Though the ability to have 2 different pages, one for **latest stable version** and one for the **latest pre-release version** is a fair point.

**Comment by jakemac53** [comment]
Hmm, to me it seems that they should be ordered by release date?

**Comment by jakemac53** [comment]
These changes are making pre-release versions extremely difficult to discover, and are causing significant confusion for polymer/polymer_elements users.

**Comment by mkustermann** [comment]
@jakemac53 This should be implemented now. If you have a suggestion on how to improve the UI let us know. 

We will only show the latest stable and latest pre-release version if there is a newer pre-release version available. So for most packages nothing changed.

**Comment by jakemac53** [comment]
Thanks!

It would be nice to also see this on the search results page (https://pub.dartlang.org/search?q=polymer for instance).

Also, if you click `versions` from the pre-release page, you don't see the pre-release versions at the top (its just the normal versions page).

**Comment by mkustermann** [comment]
> It would be nice to also see this on the search results page (https://pub.dartlang.org/search?q=polymer for instance).

I'll look into that.

> Also, if you click versions from the pre-release page, you don't see the pre-release versions at the top (its just the normal versions page).

I can certainly change the ordering if the version a user is looking at is a pre-release version. But otherwise I've been asked to use pub's priority ranking for the versions (instead of semantic version ordering) -- see my [comment here](https://github.com/dart-lang/pub-dartlang-dart/issues/53#issuecomment-229422120).

**Comment by mkustermann** [comment]
@isoos Maybe you want to take a look at this?

It should be pretty simple: Once we get search results, instead of looking up just the latest version [here](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/search_service.dart#L82) we would also search for the latest pre-release version.

Though at some point we probably want to get rid of the current search implementation, which uses Google's custom search implementation, and replace it by some custom made -- there is a lot of improvement potential here.
