### ISSUE TITLE
Unclear error when package contains no entrypoints

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dartlang-dart#49]
_From @maxwellpeterson-wf on March 22, 2016 17:55_

If you try to publish a package that does not have any `.dart` files in `lib/`, the following happens:

``` bash
Uploading... (5.1s)
Bad state: The transaction has already been committed..
```

This happens because the `libraries` property on the `PackageVersion` entity does not get set, so the commit actually fails.

``` bash
Error while committing: ApplicationError: Property "libraries" has no value., #0      _validateResponse.<anonymous closure> (package:googleapis_beta/src/common_internal.dart:880:11)
```

It would be great if there was a more clear error presented when this happens :)

_Copied from original issue: dart-lang/pub#1398_

**Comment by maxwellpeterson-wf** [comment]
This looks like more of an issue with the datastore API: https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/41

**Comment by mkustermann** [comment]
@maxwellpeterson-wf Are you using the [pub-dartlang-dart](https://github.com/dart-lang/pub-dartlang-dart) app for running your own pub server (and use the `package:gcloud/src/datastore_impl.dart` implementation)? 

If so, I could imagine that this is in fact https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/41. Our deployed version of the [pub-dartlang-dart](https://github.com/dart-lang/pub-dartlang-dart) app is using the native protobuf APIs which AppEngine provides (provided by `package:appengine`) and I think we can commit a `PackageVersion` with no libraries.

**Comment by maxwellpeterson-wf** [comment]
Yes, we have it deployed to a GCE instance for now so that we can firewall it off to our office IPs and VPN. Once [OAuth2 support is added for `pub get`](https://github.com/dart-lang/pub/pull/1335#issuecomment-171719983) we will go back to an AppEngine deployment. Good to know that it won't be an issue then.

I did end up changing the `encodeValue` method of the `CompatibleListProperty` on our fork to return `null` instead of `[]` [here](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/model_properties.dart#L130-L132), and that allows us to publish with no libraries.

**Comment by isoos** [comment]
I believe this issue can be closed. I've tried to upload an empty package (no `lib/` directory, only `bin/`), and it works just fine.
