### ISSUE TITLE
"Invalid upload: no pubspec.yaml file" when trying to publish a package

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dartlang-dart#55]
_From @Andersmholmgren on August 16, 2016 7:6_

I am trying to publish a new version of https://bitbucket.org/aholmgren/dart_jwt, a package that I have published many times before. For some reason it keeps failing

```
pub publish
Publishing dart_jwt 0.5.2 to https://pub.dartlang.org:
|-- .gitignore
|-- AUTHORS
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- bitbucket-pipelines.yml
|-- lib
|   |-- dart_jwt.dart
|   '-- src
|       |-- codec.dart
|       |-- jose.dart
|       |-- jwa.dart
|       |-- jws.dart
|       |-- jwt.dart
|       |-- jwt_claimset.dart
|       |-- util.dart
|       '-- validation_constraint.dart
|-- pubspec.yaml
'-- test
    |-- all_tests.dart
    |-- jwa_test.dart
    |-- jwt_test.dart
    '-- run.sh

Looks great! Are you ready to upload your package (y/n)? y
Uploading... (3.7s)
Invalid upload: no pubspec.yaml file.
```

_Copied from original issue: dart-lang/pub#1442_

**Comment by mkustermann** [comment]
@Andersmholmgren May I ask what version of the pub client are you using? It might be [this bug in the pub client](https://github.com/dart-lang/pub/issues/1321#issuecomment-134994150).

**Comment by Andersmholmgren** [comment]
```
> pub --version
Pub 1.19.0-dev.6.0
```

**Comment by mkustermann** [comment]
@Andersmholmgren I've tried to reproduce this but haven't succeeded so far.

Since the server code hasn't changed in a long time, I strongly suspect that something on the client side is different. I've temporarily added some debugging logic on the server which might help understand where the issue lies. Could you try to publish one more time?

I'm also interested in the following: What OS do you use and what version of tar do you have?

**Comment by Andersmholmgren** [comment]
@mkustermann I just retried then

I'm on mac osx 10.11.6

> tar --version
> bsdtar 2.8.3 - libarchive 2.8.3

**Comment by mkustermann** [comment]
@Andersmholmgren  Thank you for trying again.

Now I can confirm my suspicion: It must in fact be an issue on the client side. The tarball which got uploaded during your publish attempt is simply empty.

I've tried to reproduce it by checking out the `dart_jwt` package and using the same version of pub and upload it from a mac. Unfortunately it didn't reproduce. 

So I suspect there must be something you did differently than me OR the pub client has different behavior on you machine due to some configuration (for example pub acts differently depending on a `.gitignore` file, maybe it has some other magic as well).

Unfortunately I cannot help debug the client side, because I just don't know how pub is implemented.

I'm therefore bouncing this back to https://github.com/dart-lang/pub/issues/1442  @nex3.
