### ISSUE TITLE
example tab gone missing

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#603]
We added this back in https://github.com/dart-lang/pub-dartlang-dart/issues/186. But I don't see it anymore (both current and experimental site)?

**Comment by mit-mit** [comment]
cc @kevmoo @isoos

**Comment by isoos** [comment]
I think we still have it, but only if you have a recognized example file, like `example/example.dart` or `example/$package.dart`. Do you have a package where we should have recognize it but we didn't?

**Comment by isoos** [comment]
Just checked with a recently uploaded package: both [old](https://pub.dartlang.org/packages/combinator#pub-pkg-tab-example) and [new](
https://pub.dartlang.org/experimental/packages/combinator#-example-tab-) has an example tab. If there is a specific file that is not recognized, please reopen.

**Comment by mit-mit** [comment]
Ah, looks like this might be Flutter specific. For Flutter plugins, the example is often a complete Flutter app, and this the example is in `example/lib/main.dart`, e.g.:
https://github.com/flutter/plugins/blob/master/packages/url_launcher/example/lib/main.dart

**Comment by isoos** [comment]
Eh, that is an interesting bug:
- we do use `example/lib/main.dart` as [candidate file for examples](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/utils.dart#L211), but:
- the code part where we look up the [names](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/frontend/backend.dart#L611) only has a filtered list, because the [listTartball](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/utils.dart#L34) method has a level restriction in it, and we've only listed the files only the first two directory level.

We'll do the (1) fix in the code and (2) backfill the packages.

**Comment by isoos** [comment]
@mkustermann, @kevmoo: After https://github.com/dart-lang/pub-dartlang-dart/pull/608 gets merged and deployed, please run the `./bin/tool/backfill_examples.dart` script, AFAICT without any parameters will be fine.

**Comment by mit-mit** [comment]
Thanks for the prompt investigation!

**Comment by kevmoo** [comment]
Running now...

**Comment by kevmoo** [comment]
There we go: https://pub.dartlang.org/experimental/packages/url_launcher#-example-tab-

**Comment by mit-mit** [comment]
Excellent, thanks

**Comment by isoos** [comment]
Unfortunately we can't close this, as the change wasn't deployed yet (AFAICT). The tool needs to run again after the deploy (although it can be aborted after a couple hundred packages that cover the past week's uploads).
