### ISSUE TITLE
High priority: mark packages with invalid pubspecs as invalid

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dartlang-dart#62]
In 1.21.0, a version of pub will release with the latest `yaml`, which (correctly) fails to parse documents that contain mappings with duplicate keys. Unfortunately, we're seeing that some historical pubspecs have duplicate keys, and these are causing problems for the pub client (see #1479). Worse still, the client can't efficiently avoid this, since during version solving it only consumes pubspecs in JSON form from pub.dartlang.org.

In order to solve this, pub.dartlang.org should somehow prevent pub from seeing package versions with busted pubspecs. Some ideas for doing so:

1. Just delete the busted versions. This kind of sucks, since pub.dartlang.org is the canonical location so we may be deleting valuable user data.
2. Hack the packages to remove the duplicate mapping keys. This may be quite difficult, and would violate the principle that package versions are immutable.
3. Don't include busted versions in API calls that list all versions for a package. This would avoid actually deleting the code, and the packages would still show up on the website, but pub would no longer see them. However, it may still cause problems if a user runs "pub get" on a package that's locked a busted version.

The server should also reject any new packages that have duplicate keys, but this should be as simple as upgrading `yaml` to the latest version.

**Comment by whesse** [comment]
Is this a 1.21 release blocker?  If not, and it is just urgent, let us know.  @mit-mit @kevmoo @mkustermann

**Comment by mit-mit** [comment]
> see #1479

This bug link did not resolve, which repo is that number in?

**Comment by whesse** [comment]
https://github.com/dart-lang/pub/issues/1479

**Comment by whesse** [comment]
Does the request to the pub server include an api version number, that could indicate whether it will accept packages with duplicate keys or not?  If not, we should consider adding one and versioning the API.

**Comment by mkustermann** [comment]
So as a first step I will do some analysis and find out how many already published (package,version) tarballs have an invalid yaml file.

=> If there are very few and all of those which have the issue are owned by us, then I would tend to rewrite the tarballs

Otherwise I'll think about how to solve this differently.

**Comment by mkustermann** [comment]
The data shows there are 21 affected packages and 151 affected (package, version) tarballs which have pubspec files which do not parse with the latest package:yaml.

**Comment by mit-mit** [comment]
Isn't this a breaking change in pub? Did we announce it? Can we roll it
back and provide more notice?

**Comment by kevmoo** [comment]
It is a breaking change. We did not announce it. I'll pow-wow w/ @nex3 and @dgrove

**Comment by kevmoo** [comment]
We could. We could restrict the version of `yaml` that we pull into the SDK. That'd do it – I think.

Maybe we'd have to do it on the pub site, too?

**Comment by nex3** [comment]
I'm okay with rolling back the `yaml` version in the SDK for this release so have time to get our ducks in a row—I didn't realize when I added it that it would break `pub get`. I think pub.dartlang.org should be on the latest version, though, so we don't have anyone uploading new broken packages.

**Comment by mkustermann** [comment]
Changing the server to just ignore these (package, version) uploads poses the issue that there is at least one **package** which would then simply **no longer exist** (because all it's uploads have the issue). Also carrying around this extra logic in the server forever that some (package, version) uploads should be disabled, seems like a very unattractive solution to me.

So my suggestion is the following:
  * We prevent new duplicate-key pubspecs to be uploaded in both the pub client code and the server code
  * We let the pub client be lenient (exactly as it has been during the last years) in accepting these pubspec files for version resolution
  * We reach out to the authors of the affected packages and clarify if it is okay if we rewrite the tarballs for them or if they would mind to re-upload with patch releases (in which case we could delete the old invalid uploads)

@nex3 @mit-mit @whesse WDYT?

**Comment by whesse** [comment]
We have reverted the YAML package version, so the pub client is lenient again.
In making the pub server more strict, so it rejects uploads with duplicate keys, it would
be tricky to import two versions of the yaml package at the same time, so I would use the existing yaml parser and write additional code to check for duplicate keys.

**Comment by nex3** [comment]
@mkustermann I don't think keeping the client lenient is a viable long-term strategy. The `yaml` package aims to be totally spec-compliant, and the spec is unambiguous about duplicate keys being errors.

I don't think we have to make the server too hacky to accommodate this, though. Marking packages as not auto-discoverable without actually deleting them is something people have wanted for a long time, and the same logic could form the foundation for that as well.

> Changing the server to just ignore these (package, version) uploads poses the issue that there is at least one **package** which would then simply **no longer exist** (because all it's uploads have the issue). Also carrying around this extra logic in the server forever that some (package, version) uploads should be disabled, seems like a very unattractive solution to me.

Which package is this? We should reach out to the author and make sure that they update it as soon as possible.

**Comment by mkustermann** [comment]
> @mkustermann I don't think keeping the client lenient is a viable long-term strategy.

I wasn't proposing that we keep this forever. Since Bill's revert of the yaml package upgrade, it is in fact lenient again. Just with the downside that the client does not give a nice error now when trying to upload an invalid yaml file now (though it could).

> Marking packages as not auto-discoverable without actually deleting them is something people have wanted for a long time

Not sure what you mean by auto-discoverable. Either it's discoverable (on the web ui and via "pub get") or not. Having the web UI show a package but make "pub get" not be able to retrieve it would be very confusing for users. So we would also exclude it in the web UI. Which leaves it non-discoverable. Effectively dead. Do you see a good use case for non-discoverable packages?

> Which package is this? We should reach out to the author and make sure that they update it as soon as possible.

I think we should reach out to all authors once we agreed upon a good solution.

This is also an issue for users which have narrow constraints or even pin-pointed versions (for example docker images which used to build might no longer build).

What are the downside to repairing the (package, version) uploads? That sounds like a much better solution to me.

@kevmoo @mit-mit @nex3 Thoughts?

**Comment by nex3** [comment]
> I wasn't proposing that we keep this forever. Since Bill's revert of the yaml package upgrade, it is in fact lenient again. Just with the downside that the client does not give a nice error now when trying to upload an invalid yaml file now (though it could).

Oh, I see. I definitely agree that we shouldn't change the client behavior for 1.21.

> Not sure what you mean by auto-discoverable. Either it's discoverable (on the web ui and via "pub get") or not. Having the web UI show a package but make "pub get" not be able to retrieve it would be very confusing for users. So we would also exclude it in the web UI. Which leaves it non-discoverable. Effectively dead. Do you see a good use case for non-discoverable packages?

What I'm specifically suggesting is removing it from the `api/packages/$package` API endpoint. It would still be accessible from `api/packages/$package/versions/$version` so users who already have it in their lockfiles can continue to access it, and from the web UI (although probably with a visual indicator that it's been yanked). This is a pretty common feature among package managers; I think we've mostly managed to avoid it so far because our ecosystem is still small.

> I think we should reach out to all authors once we agreed upon a good solution.

No matter what solution we end up with, authors will need to publish new versions without duplicate keys. We should notify them as soon as possible so that these versions can get into the ecosystem quickly.

> What are the downside to repairing the (package, version) uploads? That sounds like a much better solution to me.

It breaks assumptions that tools might (reasonably) make about uploads being immutable. For example, when we pull packages in to the SDK or Google's internal repository, we take the sources from Git rather than pub on the assumption that they're identical. We shouldn't erode that trust.

**Comment by kasperl** [comment]
In this instance, I think we should be more worried about the hard-to-foresee issues that might arise by hacking around the issue in the server than the immutability of uploads.

**Comment by nex3** [comment]
@kasperl By "hacking", do you mean yanking the packages? Yanking is something that's well-understood and implemented across many different package servers in different languages, and something we'll definitely need to add support for at some point. It seems like an elegant way of solving the problem.

**Comment by kasperl** [comment]
If the suggested fix for this issue is to implement a new feature in pub across the client and server (_yanking_), I'd like to see a design for that written down, agreed upon, and implemented and tested by a team that covers both the client and the server side. As far as I can tell, the proposed functionality is far from trivial to get right:

http://blog.rubygems.org/2015/04/13/permadelete-on-yank.html
http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

Sorry for using the overloaded term "hacking".

**Comment by nex3** [comment]
Those articles raise good questions that should definitely be addressed when we add a public-facing yank feature. But I don't think they should block handling the immediate problem of broken versions.

**Comment by kasperl** [comment]
**Update:** We discussed the issue yesterday and decided to move forward with the in-place repairing of packages. First step is to e-mail the authors and make them aware of the situation.

**Comment by mkustermann** [comment]
Almost all affected versions have been fixed (those we received the package authors permission).

The invalid `pubspec.yaml` files have been changed to comment out invalid the duplicate sections. Newer versions of `package:yaml` will now parse the files **in the same way old versions did**.

**Comment by nex3** [comment]
Is `pub.dartlang.org` using the newest `yaml` package version now, so it'll reject new packages with invalid pubspecs?

**Comment by mkustermann** [comment]
@nex3 It has been doing so for the last month, more specifically since https://github.com/dart-lang/pub-dartlang-dart/commit/a0fc55c4855a1863bb3326c320bef4f93ac7cfe9 (which upgraded to `package:yaml` version `2.1.12 `). 

That being said, the error message could probably be a bit nicer (iirc we just pass along the exception to the client)
