### ISSUE TITLE
[gde review] Feedback on "experimental"

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/pub-dartlang-dart#698]
Homepage:

This might be one of the "first contacts" of a new developer with Dart. List of top packages might be confusing to them. "angular_router" is the most important package?
I would keep the three column layout and the "cards", but I would curate content by hand  - TOP3 Flutter, Web, Server packages. Show them Flutter has firebase plugin, web has angular 4, server has shelf or whatever ... This is creating first impression. And you can update it once in 3 months, this doesn't change that often.

Topic buttons below the search field doesn't do what I expect, they seem to be connected with the search, not with the TOP packages below. IMHO clicking on these buttons should lead to search results (with empty search = top packages for selected platform). Like this: https://pub.dartlang.org/experimental/flutter/packages?q=

Search results:
Generally ok, score is a bit confusing at the first time, maybe add "%" sign?

Overall - definitely step in the right direction, please consider my UX notes on the homepage.

**Comment by isoos** [comment]
Thanks for the feedback!

- The list of top packages is under refinement (e.g. #700), @kevmoo may comment on the fixed-list suggestion.
- The query problem should be fixed by #701.
- The '%' doesn't really reflects what we have here, because popularity is across the packages: you can't have every package to have 100% popularity (or 100% overall).

**Comment by isoos** [comment]
Closing this, as most of it was addressed, and it seems that the landing page won't change much in the near future.
