### ISSUE TITLE
Check why readme/changelog entries can exist with a content of null

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#7]
The fix for https://github.com/dart-lang/pub-dartlang-dart/issues/2 just added an additional check for `null`. However this should not be needed as the `FileObject`(s) (returned by the `readme` and `changelog` getters on `PackageVersion`) should not exist in that case.

**Comment by isoos** [comment]
I've checked the history of the related sources (`parseAndValidateUpload()` and `readTarballFile()`), and I don't see obvious bugs in our code.

The most likely explanation could be that when calling the external process (`tar`), for some reason ProcessResult.stdout contained `null`. I've seen a few Process-related fixes in the SDK around the time of this issue, one of them might have fixed this too.

I believe this issue could be closed. If you think further precaution is needed, we could:
- log when a null value is returned
- switch to using the package [archive](https://pub.dartlang.org/packages/archive), because it supports native `tar` processing.

**Comment by mkustermann** [comment]
Let's close the issue, and re-open if we see it again.
