### ISSUE TITLE
Consider rolling SDK back to pre-2.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#713]
Angular is "dinged" now for using an API that was changed in early Dart v2 - https://pub.dartlang.org/experimental/packages/angular#-analysis-tab-

We accidentally kept rolling to the latest dev release and never dug in here.

Could we try rolling things back to 1.24.2?

I'm a bit scared about this. We'd have to figure out what to do w/ flutter, too.

**Comment by kevmoo** [comment]
CC @isoos – we should discuss

**Comment by alorenzen** [comment]
Going forward, we should support multiple SDKs so that we can actually honor the SDK constraint in the pubspec. Though maybe that should be tracked as a separate issue?

**Comment by kevmoo** [comment]
> Going forward, we should support multiple SDKs so that we can actually honor the SDK constraint in the pubspec. Though maybe that should be tracked as a separate issue?

Yup!

**Comment by isoos** [comment]
I haven't checked, but based on the message, I think angular's issue is only a type cast (`dynamic` vs. `R`), and should be easy to do a patch release to fix it.

Re multiple SDK support: I think a few months back one of the guidelines we were using for analysis was that we only care about the results with the latest stable tooling (2.0-dev will be an exception). Otherwise it would be hard for somebody or for our scoring to compare two packages via their analysis. It would make everything (running, storing, displaying the analysis) complex, and it would provide very little benefit (a feel-good period that nothing is broken, while the library is not really supported on the latest versions).

**Comment by isoos** [comment]
One thing that would be an alternative here is to keep running the latest SDK (2.0-dev for the time being), and if we see errors with a package, we also run the analysis with the previous stable (1.24.2 for now). We keep the better result, and if it is coming from the earlier version, we average the scores. 

Part of it is SDK-independent (like the library scanner), but most of the code health and some of the maintenance can be compensated with this method.

@mkustermann, @kevmoo what do you think?

**Comment by mkustermann** [comment]
There's a few things here:

  * Is the sdk version we are talking about the one in the `Dockerfile` base image? If so, I think this version should be independent from the one we use for running pana / ... For example for flutter, we need to use the sdk version that our flutter checkout uses (e.g. `flutter packages analyze` or what it was called, is using it's own sdk)
  * I think we should use the newest sdk version which matches the `pubspec.yaml`'s sdk constraint (if the author doesn't want his package to run on newer sdks, the sdk constraint should say so)

Regarding the last point: We are in a special situation, because we basically no longer release any stable versions until 2.0, which makes our dev releases the only thing that moves forward. We also want our package authors to follow along with the transition to 2.0, so I think it makes sense to use newest dev releases for running pana.

Also generally speaking, since we have an ever-green-system, it is questionable whether we should support running pana with older versions of the sdk: We don't do bugfixes for older versions of the sdk either. So after the transition to 2.0 I would recommend just continue to use the latest (stable) sdk for analyzing.

Though @kevmoo is the person to make the call here.

**Comment by kevmoo** [comment]
I rolled pkg/angular v4 and it's looking better now.

Let's hold off doing anything fancy here unless we run into other issues.

**Comment by mit-mit** [comment]
We discussed this, and for now we think it's critical that we get packages upgraded to 2.0 even if that introduces a bit of pain. Closing as won't fix.
