### ISSUE TITLE
Reorganize the file structure

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#79]
Move `app` to root.
Move contents of `static` into `web`

A more typical package layout.

**Comment by mkustermann** [comment]
There is a reason for the layout and I don't think I want to change it - it would be harmful in fact.

**Comment by kevmoo** [comment]
Would love to understand why at least... 😄

**Comment by mkustermann** [comment]
Because **very often** I need to use an un-published version of a package (e.g. bugs in `package:markdown` or a not-yet-released version of `package:appengine`, then I add a `pkgs/<custom-pkg>`, change `Dockerfile` and use a `dependency_override` in `pubspec.yaml`).

We have no support for nested packages, so I cannot have standard layout.

**Comment by kevmoo** [comment]
Ah...that's helpful 😄

**Comment by kevmoo** [comment]
...but we could easily move `static` to `app/web` 😁
