### ISSUE TITLE
Display Author in the result list

### ISSUE THREAD

**Issue by BorisNaguet** [dart-lang/pub-dartlang-dart#814]
Hello,

Nice new version of the site :)

In the search result list, I'd like to have the Author(s) of each result (after version/date/type).

I think it was available in the previous version, and it's very useful to find packages from "Dart Team", "Flutter Team", or from a well known and active contributor, because sometimes it's more important to know that it'll be supported for a while, and issues and PR will be managed quickly, than other things.
 Also, sometimes there are some groups of packages from the same author, that are made to work together.

Thanks

**Comment by isoos** [comment]
Thanks for the feedback!

IIRC this was discussed and the idea was we don't put the authors there, because we have now the score and also the platform info to put there. A single author wouldn't be an issue, but 2+ makes it really wide and feels weird. Hopefully the score is a good proxy for quality. 

The package groups have several resolution:
- you can use `package:xyz` to search for packages starting with `xyz` (usually groups have the pattern of `xyz_a`, `xyz_b`
- we are working on providing search via e-mail addresses
- #715
