### ISSUE TITLE
Be clear if someone tries to use a search qualifier that isn't supported.

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#826]
If I put in `mail:bob@gmail.com` or something, tell me "`mail` is not a supported qualifier see http://XYZ for the list of supported qualifiers".

This info should be sent back from the search service – so it's based on what the currently deployed service supports, etc.

**Comment by isoos** [comment]
I think this is going to be too complex to put it in there (esp. that the feature is reported back from the search service). We could format and display the parsed query on the `frontend`, and then only the window while they are not in feature parity is the issue - which shouldn't be too large issue, because deploying the search service first should be always safe.
