### ISSUE TITLE
author/uploader: make the text a mailto: link if it's an email address

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#827]
Just what folks expect – I'm fine w/ not doing it on regular text. I hate being surprised by a mail popup when I thought I'd navigate to a site.

**Comment by isoos** [comment]
Couple of issues:
- inconsistency when doing on regular text: people expected navigation on the site
- inconsistency when not doing on regular text: (a) either the mail icon gets removed, or (b) there are two ways to achieve the same
- it will look weird if two lines of authors differ.

I've started with everything being a link, but eventually I liked the two icons better, because it can be consistent across the different use cases. I was thinking to trim the `@domain.com` part, but in the end it looks useful enough.

**Comment by kevmoo** [comment]
Fair enough. Wanted to discuss.

@mit-mit FYI
