### ISSUE TITLE
Improve exact match search

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub-dartlang-dart#865]
If I search for a package with the exact name it should show up early in the list, even if it has a low popularity score. Searching for `build_config` today it doesn't show up until page 2.

**Comment by isoos** [comment]
This happens because overall score has more weight than the text match score. If you look at the text-only results, the package is the first: https://pub.dartlang.org/packages?q=build_config&sort=text

One obvious thing I can think of is to check for exact match of the package name, and if there is one (and there are not other phrases), than we put it as the first results, regardless of the overall score. Question is: shall we do that only when we are on the default sort, or shall we do it regardless of sort?
