### ISSUE TITLE
`outdated` package showing up as `[awaiting]` on package site

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#888]
See https://dartlang-pub.appspot.com/packages/shelf_rpc

and https://analyzer-dot-dartlang-pub.appspot.com/packages/shelf_rpc/0.0.3+2

Oops?

**Comment by isoos** [comment]
We have more than one issue here:
- the text that "We analyzed this package...", while we are not doing it at all
- the `[awaiting]` flag on the package extract and the package show page
- there is a bug in the logic that decides not to analyze too old packages and we skip the latest stable ones too

I believe that the `[awaiting]` will be resolved if we fix the later one, because the awaiting is coming from the data of the latest stable.

**Comment by isoos** [comment]
Most of this is fixed now, there is still an issue with the `[awaiting]` label on pages like https://dartlang-pub.appspot.com/packages/shelf_rpc/versions/0.0.3

**Comment by mit-mit** [comment]
@isoos @jakobr-google looks like this is fixed now?

**Comment by isoos** [comment]
yeah, fixed.
