### ISSUE TITLE
Not seeing most recent version of package - see path

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#9]
Looking at `path`

The latest version is 1.3.5 - https://dartlang-pub.appspot.com/packages/path

https://buildbot-dart-2015-04-21-dot-dartlang-pub.appspot.com/packages/path

But on the dev site it shows up as 1.1.0

**Comment by sethladd** [comment]
Also not seeing the latest version of grinder. https://pub.dartlang.org/packages/grinder

Should be 0.7.0.

(I'm looking at the new version, because I see "Instance of" in the HTML title)

![screen shot 2015-04-21 at 8 17 44 pm](https://cloud.githubusercontent.com/assets/5479/7266740/66145c9c-e863-11e4-8f46-29c5cab8f653.png)

**Comment by sgjesse** [comment]
Fixed in 730d519a87c903c1de6fb54507fbc08cc746686b.
