### ISSUE TITLE
SEO seems lacking

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#948]
I wonder if there is anything we can do to promote Pub pages more in searches?

For example, googling for 'flutter send sms' shows pub as the fourth result, way after github:
https://www.google.dk/search?q=flutter+send+sms

**Comment by isoos** [comment]
Based on the Moz OSE, I think we have very few inbound links for that package, e.g. [url_launcher](https://moz.com/researchtools/ose/links?site=https%3A%2F%2Fpub.dartlang.org%2Fpackages%2Furl_launcher&filter=&source=external&target=page&group=0&page=1&sort=page_authority&anchor_id=&anchor_type=&anchor_text=&from_site=) vs [angular](https://moz.com/researchtools/ose/links?site=https%3A%2F%2Fpub.dartlang.org%2Fpackages%2Fangular&filter=&source=external&target=page&group=0&page=1&sort=page_authority&anchor_id=&anchor_type=&anchor_text=&from_site=) (note: I think there is a daily limit on how many URLs the OSE analyses).

Opportunities for improvements outside of pub site:

- GitHub repository can have one URL that points to the package, e.g. in the `pana` repo:
  <img width="789" alt="screen shot 2018-02-01 at 9 19 16" src="https://user-images.githubusercontent.com/4778111/35668241-06e12738-0731-11e8-922a-8241e99cb150.png">
  Unfortunately this is not great for flutter where the packages live in the single big repo.

- StackOverflow answers should be extended with links to the package page on pub.

- Our internal guides and tutorials should link to the package pages whenever it is natural to do so.

Opportunities for us:

- Increase the number of packages on the listing/search pages. This will reduce the distance from the index page for packages and hopefully increase their score.

- Add some attributes for the indexing pages that keeps the out of the index and passes their pagerank to the linked packages.

- With documentation on a separate domain, we can link back to the package, and provide one additional linkback from external domains.

**Comment by kevmoo** [comment]
I've pushed through a number of changes to help with https://www.google.com/webmasters/tools/html-suggestions?hl=en&authuser=0&siteUrl=https://pub.dartlang.org/

(I think only @mit-mit will have access)

**Comment by kevmoo** [comment]
This is annoying: `dart test package`

- test package homepage - solid
- Dart testing page – solid
- test_runner: very deprecated
- unittest: very deprecated
- matcher: related-ish
- dart_dev: related-ish

I know Google tries to fold up pages that seem to overlap since the contents overlap so much.

GitHubs links (at the top of the page) have `rel="nofollow"` and the package site doesn't if the GitHub page "wins" in Google's eyes.

It might be interesting/good to make all user-provided links (homepage, documentation, everything in the readme/changelog) as `rel="nofollow"`

![screen shot 2018-02-01 at 7 22 39 pm](https://user-images.githubusercontent.com/17034/35715094-5496e4dc-0785-11e8-947a-3eb8f609ec81.png)

**Comment by isoos** [comment]
> It might be interesting/good to make all user-provided links (homepage, documentation, everything in the readme/changelog) as rel="nofollow"

I'd vote against this. Of my N=4 sample of non-Googler package authors, everybody loves the fact that they get a small SEO benefit of the links from their `README` or `homepage` attribute. If we really want to restrict these, I'd keep the `rel=follow` on the `homepage` (and introduce a `repository` link alongside it).

> I wonder if the GitHub page "wins" in Google's eyes because of the links that it counts.

I believe that the domain authority (importance) rank of github.com is certainly better than pub.dartlang.org's. In addition to that, we have very few inbound links for the package page from authoritative sources (a few jetbrains.com and github.io pages in the package:test case).

Compared to that, follow/nofollow links barely move the needle, and it is not that github page wins because we link to it, rather the opposite: we loose because we have fewer inbound links.

If you check the sources of the second result (view-source:https://www.dartlang.org/guides/testing), it has around 100 `<a href=""` elements, and `package:test` is only one of them, not even prominent (around the 60% of the page). If I were to optimize SEO, I'd first look for paces like this.

**Comment by kevmoo** [comment]
I buy it. :-)

**Comment by kevmoo** [comment]
Looking better – at least for `dart test package`

![screen shot 2018-02-21 at 10 49 00 am](https://user-images.githubusercontent.com/17034/36499006-dd467c74-16f4-11e8-9547-01b11330b658.png)

**Comment by isoos** [comment]
Yeah, looks like Google picks up the version and other metadata too. It is also the first result on bing.

**Comment by kevmoo** [comment]
![screen shot 2018-03-08 at 12 52 35 pm](https://user-images.githubusercontent.com/17034/37175875-aee2eff2-22cf-11e8-93de-27db8c06101d.png)

Two more ideas:

1) Expand the description on the homepage.
2) Exclude `/packages` search/browse pages...

**Comment by isoos** [comment]
Yeah, searching for `site:pub.dartlang.org "page 3"` seems to be too much.

**Comment by mit-mit** [comment]
How about this description? 

"Pub is the packager for the Dart programming language, containing reusable libraries & packages for Flutter, AngularDart, and general Dart programs."
